const quizData = [
{ en: "Once", sans: "एकदा" },
{ en: "one", sans: "एकः" },
{ en: "cowherd boy", sans: "गोपालकबालकः" },
{ en: "of the village", sans: "ग्रामस्य" },
{ en: "near", sans: "समीपे" },
{ en: "on a mountain", sans: "पर्वते" },
{ en: "sheep", sans: "मेषान्" },
{ en: "took care of", sans: "अपालयत्" },
{ en: "He", sans: "सः" },
{ en: "mostly", sans: "प्रायशः" },
{ en: "alone", sans: "एकाकी" },
{ en: "was", sans: "आसीत्" },
{ en: "Therefore", sans: "तस्मात्" },
{ en: "he", sans: "सः" },
{ en: "sometimes", sans: "कदाचित्" },
{ en: "to play", sans: "क्रीडितुम्" },
{ en: "wished", sans: "इच्छति" },
{ en: "was", sans: "स्म" },
{ en: "One day", sans: "एकस्मिन् दिने" },
{ en: "loudly", sans: "उच्चैः" },
{ en: "cried", sans: "अक्रन्दत्" },
{ en: "A wolf is coming", sans: "वृकः आगच्छति" },
{ en: "Protect me", sans: "मां रक्षन्तु" },
{ en: "His", sans: "तस्य" },
{ en: "cry", sans: "क्रन्दनं" },
{ en: "having heard", sans: "श्रुत्वा" },
{ en: "the villagers", sans: "ग्रामवासिनः" },
{ en: "running", sans: "धावित्वा" },
{ en: "came", sans: "आगतवन्तः" },
{ en: "But", sans: "किन्तु" },
{ en: "there", sans: "तत्र" },
{ en: "wolf", sans: "वृकः" },
{ en: "was not", sans: "न आसीत्" },
{ en: "The boy", sans: "बालकः" },
{ en: "them", sans: "तान्" },
{ en: "seeing", sans: "दृष्ट्वा" },
{ en: "laughed", sans: "अहसत्" },
{ en: "The villagers", sans: "ग्रामवासिनः" },
{ en: "disappointed", sans: "निराशाः" },
{ en: "became", sans: "अभवन्" },
{ en: "After a few days", sans: "कतिपयदिनानन्तरं" },
{ en: "again", sans: "पुनः" },
{ en: "went", sans: "अगच्छन्" },
{ en: "Again", sans: "पुनरपि" },
{ en: "not", sans: "न" },
{ en: "angry", sans: "क्रुद्धाः" },
{ en: "On another day", sans: "अन्यस्मिन् दिने" },
{ en: "actually", sans: "वस्तुतः" },
{ en: "came", sans: "आगच्छत्" },
{ en: "the sheep", sans: "मेषान्" },
{ en: "attacked", sans: "आक्रमत्" },
{ en: "frightened", sans: "भयभीतः" },
{ en: "became", sans: "अभवत्" },
{ en: "said", sans: "अवदन्" },
{ en: "this", sans: "अयं" },
{ en: "boy", sans: "बालकः" },
{ en: "falsely", sans: "मिथ्या" },
{ en: "speaks", sans: "वदति" },
{ en: "they", sans: "ते" },
{ en: "did not go", sans: "न अगच्छन्" },
{ en: "The wolf", sans: "वृकः" },
{ en: "some", sans: "केचन" },
{ en: "took away", sans: "नीतवान्" },
{ en: "his own", sans: "स्वस्य" },
{ en: "fault", sans: "दोषं" },
{ en: "understood", sans: "अवगच्छत्" },
{ en: "learned", sans: "अधीतवान्" },
{ en: "that", sans: "यत्" },
{ en: "People", sans: "जनाः" },
{ en: "those who lie", sans: "मिथ्यावादिनः" },
{ en: "in the words", sans: "वचनेषु" },
{ en: "do not believe", sans: "न विश्वसन्ति" },
];
