const quizData = [
{ en: "Once", sans: "एकदा" },
{ en: "one", sans: "एकः" },
{ en: "crow", sans: "काकः" },
{ en: "very", sans: "अतिशयेन" },
{ en: "thirsty", sans: "तृषितः" },
{ en: "was", sans: "आसीत्" },
{ en: "He", sans: "सः" },
{ en: "everywhere", sans: "सर्वत्र" },
{ en: "of water", sans: "जलस्य" },
{ en: "search", sans: "अन्वेषणं" },
{ en: "did", sans: "कृतवान्" },
{ en: "Finally", sans: "अन्ते" },
{ en: "he", sans: "सः" },
{ en: "a", sans: "एकं" },
{ en: "pitcher", sans: "घटं" },
{ en: "saw", sans: "दृष्टवान्" },
{ en: "In the pitcher", sans: "घटे" },
{ en: "a little", sans: "अल्पं" },
{ en: "water", sans: "जलम्" },
{ en: "Crow", sans: "काकः" },
{ en: "water", sans: "जलं" },
{ en: "to drink", sans: "पातुं" },
{ en: "effort", sans: "प्रयत्नं" },
{ en: "made", sans: "कृतवान्" },
{ en: "But", sans: "किन्तु" },
{ en: "of the pitcher", sans: "घटस्य" },
{ en: "below", sans: "अधः" },
{ en: "His", sans: "तस्य" },
{ en: "beak", sans: "चञ्चुः" },
{ en: "did not obtain", sans: "न प्राप्तवती" },
{ en: "thought", sans: "चिन्तितवान्" },
{ en: "Then", sans: "ततः" },
{ en: "nearby", sans: "समीपे" },
{ en: "situated", sans: "स्थितान्" },
{ en: "small stones", sans: "लघुशिलाखण्डान्" },
{ en: "one by one", sans: "एकैकां" },
{ en: "stone", sans: "शिलां" },
{ en: "taking", sans: "गृहीत्वा" },
{ en: "into the pitcher", sans: "घटे" },
{ en: "threw", sans: "क्षिप्तवान्" },
{ en: "Slowly slowly", sans: "शनैः शनैः" },
{ en: "of the water", sans: "जलस्य" },
{ en: "level", sans: "स्तरः" },
{ en: "upward", sans: "उपरि" },
{ en: "came", sans: "आगच्छत्" },
{ en: "When", sans: "यदा" },
{ en: "sufficient", sans: "पर्याप्तम्" },
{ en: "became", sans: "अभवत्" },
{ en: "then", sans: "तदा" },
{ en: "having drunk", sans: "पीत्वा" },
{ en: "thirst", sans: "तृष्णां" },
{ en: "quenched", sans: "शमितवान्" },
{ en: "very", sans: "अत्यन्तं" },
{ en: "happy", sans: "प्रसन्नः" },
];
