const quizData = [
{ en: "Once", sans: "एकदा" },
{ en: "one", sans: "एकः" },
{ en: "lion", sans: "सिंहः" },
{ en: "of the tree", sans: "वृक्षस्य" },
{ en: "under, below", sans: "अधः" },
{ en: "sleep", sans: "निद्रां" },
{ en: "does, was doing", sans: "करोति स्म" },
{ en: "At that", sans: "तस्मिन्" },
{ en: "time", sans: "समये" },
{ en: "small", sans: "लघुः" },
{ en: "mouse", sans: "मूषकः" },
{ en: "his", sans: "तस्य" },
{ en: "body", sans: "शरीरे" },
{ en: "to run", sans: "धावितुम्" },
{ en: "began", sans: "आरब्धवान्" },
{ en: "Of the mouse", sans: "मूषकस्य" },
{ en: "by the running", sans: "धावनेन" },
{ en: "of the lion", sans: "सिंहस्य" },
{ en: "sleep", sans: "निद्रा" },
{ en: "broken, interrupted", sans: "भङ्गा" },
{ en: "became, happened", sans: "अभवत्" },
{ en: "Lion", sans: "सिंहः" },
{ en: "angry", sans: "क्रुद्धः" },
{ en: "became", sans: "अभवत्" },
{ en: "He", sans: "सः" },
{ en: "mouse", sans: "मूषकम्" },
{ en: "with his own paw/claw", sans: "स्वपञ्जरेण" },
{ en: "seized, caught", sans: "अगृह्णात्" },
{ en: "Mouse", sans: "मूषकः" },
{ en: "frightened", sans: "भयभीतः" },
{ en: "requested, prayed", sans: "प्रार्थितवान्" },
{ en: "O", sans: "हे" },
{ en: "lion-king", sans: "सिंहराज" },
{ en: "please", sans: "कृपया" },
{ en: "me", sans: "माम्" },
{ en: "release", sans: "मुञ्च" },
{ en: "In the future", sans: "भविष्ये" },
{ en: "I", sans: "अहम्" },
{ en: "your", sans: "भवतः" },
{ en: "help", sans: "साहाय्यम्" },
{ en: "will do", sans: "करिष्यामि" },
{ en: "laughed", sans: "अहसत्" },
{ en: "thought", sans: "अचिन्तयत्" },
{ en: "this", sans: "एषः" },
{ en: "My", sans: "मम" },
{ en: "how", sans: "कथम्" },
{ en: "will he do", sans: "करिष्यति ?" },
{ en: "Nevertheless", sans: "तथापि" },
{ en: "he", sans: "सः" },
{ en: "having shown compassion", sans: "दयां कृत्वा" },
{ en: "released", sans: "मुक्तवान्" },
{ en: "After a few days", sans: "कतिपयदिनानन्तरम्" },
{ en: "of a hunter", sans: "शिकाऱिणः" },
{ en: "in a net", sans: "जाले" },
{ en: "fell", sans: "पतितः" },
{ en: "much", sans: "बहु" },
{ en: "effort", sans: "प्रयत्नम्" },
{ en: "made", sans: "कृतवान्" },
{ en: "but", sans: "किन्तु" },
{ en: "freed, liberated", sans: "मुक्तः" },
{ en: "not", sans: "न" },
{ en: "loudly", sans: "उच्चैः" },
{ en: "roared, cried out", sans: "अनर्दत्" },
{ en: "His", sans: "तस्य" },
{ en: "sound, roar", sans: "नादम्" },
{ en: "having heard", sans: "श्रुत्वा" },
{ en: "there", sans: "तत्र" },
{ en: "came", sans: "आगच्छत्" },
{ en: "with his own teeth", sans: "स्वदन्तैः" },
{ en: "net", sans: "जालम्" },
{ en: "to cut", sans: "कर्तयितुम्" },
{ en: "Quickly, soon", sans: "शीघ्रमेव" },
{ en: "cut", sans: "छिन्नम्" },
{ en: "and", sans: "च" },
{ en: "freed", sans: "मुक्तः" },
{ en: "said", sans: "अवदत्" },
{ en: "Friend", sans: "मित्र" },
{ en: "you", sans: "त्वम्" },
{ en: "my", sans: "मम" },
{ en: "life, lives", sans: "प्राणान्" },
{ en: "protected", sans: "अरक्षः" },
{ en: "formerly, before", sans: "पूर्वम्" },
{ en: "you", sans: "त्वाम्" },
{ en: "small, inferior", sans: "न्यूनम्" },
{ en: "considered", sans: "मन्ये स्म" },
{ en: "Now", sans: "अधुना" },
{ en: "know", sans: "जानामि" },
{ en: "that", sans: "यत्" },
{ en: "even", sans: "अपि" },
{ en: "great", sans: "महान्" },
{ en: "help, favor", sans: "उपकारम्" },
{ en: "to do", sans: "कर्तुम्" },
{ en: "is able", sans: "शक्नोति" },
{ en: "happy, pleased", sans: "प्रसन्नः" },
{ en: "they two", sans: "तौ" },
{ en: "friends", sans: "मित्रे" },
{ en: "became", sans: "अभवताम्" },
];
