const quizData = [
{ en: "Once", sans: "एकदा" },
{ en: "in the forest", sans: "वने" },
{ en: "one", sans: "एकः" },
{ en: "lion", sans: "सिंहः" },
{ en: "lived", sans: "वसति स्म" },
{ en: "He", sans: "सः" },
{ en: "every day", sans: "प्रतिदिनं" },
{ en: "many", sans: "अनेकान्" },
{ en: "animals", sans: "पशून्" },
{ en: "killed", sans: "हन्ति स्म" },
{ en: "Of the forest", sans: "वनस्य" },
{ en: "all", sans: "सर्वे" },
{ en: "animals", sans: "पशवः" },
{ en: "frightened", sans: "भयभीताः" },
{ en: "were", sans: "आसन्" },
{ en: "They", sans: "ते" },
{ en: "together", sans: "एकत्र" },
{ en: "having met", sans: "मिलित्वा" },
{ en: "thought", sans: "चिन्तितवन्तः" },
{ en: "Then", sans: "ततः" },
{ en: "they", sans: "ते" },
{ en: "to the lion", sans: "सिंहस्य" },
{ en: "near", sans: "समीपं" },
{ en: "went", sans: "गतवन्तः" },
{ en: "said", sans: "अवदन्" },
{ en: "O", sans: "हे" },
{ en: "king lion", sans: "सिंहराज" },
{ en: "you", sans: "त्वं" },
{ en: "do not kill", sans: "मा हन" },
{ en: "we", sans: "वयं" },
{ en: "one", sans: "एकं" },
{ en: "animal", sans: "पशुं" },
{ en: "to you", sans: "तव" },
{ en: "will send", sans: "प्रेषयामः" },
{ en: "Lion", sans: "सिंहः" },
{ en: "that", sans: "तत्" },
{ en: "agreed", sans: "अङ्गीकृतवान्" },
{ en: "From then on", sans: "ततः आरभ्य" },
{ en: "animal", sans: "पशुः" },
{ en: "for food", sans: "भोजनार्थं" },
{ en: "went", sans: "गच्छति स्म" },
{ en: "of a rabbit", sans: "एकस्य शशकस्य" },
{ en: "turn", sans: "क्रमः" },
{ en: "came", sans: "आगतः" },
{ en: "small", sans: "लघुः" },
{ en: "was", sans: "आसीत्" },
{ en: "but", sans: "किन्तु" },
{ en: "intelligent", sans: "बुद्धिमान्" },
{ en: "Rabbit", sans: "शशकः" },
{ en: "knew", sans: "जानाति स्म" },
{ en: "that", sans: "यत्" },
{ en: "egoistic", sans: "अहङ्कारी" },
{ en: "Therefore", sans: "अतः" },
{ en: "he", sans: "सः" },
{ en: "late", sans: "विलम्बेन" },
{ en: "went", sans: "अगच्छत्" },
{ en: "because of hunger", sans: "क्षुधया" },
{ en: "angry", sans: "क्रुद्धः" },
{ en: "became", sans: "अभवत्" },
{ en: "said", sans: "अवदत्" },
{ en: "why", sans: "किमर्थम्" },
{ en: "on the way", sans: "मार्गे" },
{ en: "another", sans: "अन्यः" },
{ en: "me", sans: "माम्" },
{ en: "stopped", sans: "अवारयत्" },
{ en: "indeed", sans: "एव" },
{ en: "of this forest", sans: "अस्य वनस्य" },
{ en: "king", sans: "राजा" },
{ en: "is", sans: "अस्ति" },
{ en: "thus", sans: "इति" },
{ en: "very", sans: "अतीव" },
{ en: "that", sans: "सः" },
{ en: "where", sans: "कुत्र" },
{ en: "come", sans: "आगच्छ" },
{ en: "I", sans: "अहं" },
{ en: "you", sans: "त्वां" },
{ en: "to him", sans: "तस्य समीपं" },
{ en: "will lead", sans: "नयामि" },
{ en: "rabbit", sans: "शशकः" },
{ en: "lion", sans: "सिंहं" },
{ en: "to a", sans: "एकस्य" },
{ en: "well", sans: "कूपस्य" },
{ en: "led", sans: "नीतवान्" },
{ en: "in this", sans: "अस्मिन्" },
{ en: "well", sans: "कूपे" },
{ en: "lives", sans: "वसति" },
{ en: "in the well", sans: "कूपे" },
{ en: "saw", sans: "अपश्यत्" },
{ en: "there", sans: "तत्र" },
{ en: "his own", sans: "स्वस्य" },
{ en: "reflection", sans: "प्रतिबिम्बं" },
{ en: "saw", sans: "दृष्टवान्" },
{ en: "His own reflection", sans: "स्वप्रतिबिम्बम्" },
{ en: "another", sans: "अन्यं" },
{ en: "lion", sans: "सिंहम्" },
{ en: "thinking", sans: "मत्वा" },
{ en: "loudly", sans: "उच्चैः" },
{ en: "roared", sans: "गर्जितवान्" },
{ en: "From the well", sans: "कूपात्" },
{ en: "echo", sans: "प्रतिध्वनिः" },
{ en: "also", sans: "अपि" },
{ en: "more", sans: "अधिकं" },
{ en: "immediately", sans: "तत्क्षणम्" },
{ en: "into the well", sans: "कूपे" },
{ en: "fell", sans: "अपतत्" },
{ en: "from that", sans: "तस्मात्" },
{ en: "well", sans: "कूपात्" },
{ en: "to come out", sans: "निर्गन्तुं" },
{ en: "not", sans: "न" },
{ en: "was able", sans: "शक्तवान्" },
{ en: "Thus", sans: "एवं" },
{ en: "died", sans: "मृतः" },
{ en: "All", sans: "सर्वे" },
{ en: "happy", sans: "प्रसन्नाः" },
{ en: "became", sans: "अभवन्" },
{ en: "by his own intelligence", sans: "स्वबुद्ध्या" },
{ en: "of the forest", sans: "वनस्य" },
{ en: "all", sans: "सर्वान्" },
{ en: "protected", sans: "अरक्षत्" },
{ en: "lesson", sans: "बोधः" },
{ en: "this", sans: "अयम्:" },
{ en: "Intelligence", sans: "बुद्धिः" },
{ en: "than strength", sans: "बलात्" },
{ en: "superior", sans: "श्रेष्ठा" },
{ en: "is", sans: "भवति" },
];
