const quizData = [
{ en: "Once", sans: "एकदा" },
{ en: "on the bank of a river", sans: "नदीतीरे" },
{ en: "one", sans: "एकः" },
{ en: "monkey", sans: "वानरः" },
{ en: "used to live", sans: "वसति स्म" },
{ en: "He", sans: "सः" },
{ en: "on a rose-apple tree", sans: "जम्बूफलवृक्षे" },
{ en: "used to live", sans: "निवसति स्म" },
{ en: "On that", sans: "तस्मिन्" },
{ en: "tree", sans: "वृक्षे" },
{ en: "sweet", sans: "मधुराणि" },
{ en: "fruits", sans: "फलानि" },
{ en: "were", sans: "आसन्" },
{ en: "One", sans: "एकः" },
{ en: "crocodile", sans: "मकरः" },
{ en: "also", sans: "अपि" },
{ en: "in that", sans: "तस्मिन्" },
{ en: "river", sans: "नद्यां" },
{ en: "Monkey", sans: "वानरः" },
{ en: "everyday", sans: "प्रतिदिनं" },
{ en: "to him", sans: "तस्मै" },
{ en: "used to give", sans: "ददाति स्म" },
{ en: "Slowly slowly", sans: "शनैः शनैः" },
{ en: "of them two", sans: "तयोः" },
{ en: "friendship", sans: "मैत्री" },
{ en: "became", sans: "अभवत्" },
{ en: "to his home", sans: "स्वगृहं" },
{ en: "having gone", sans: "गत्वा" },
{ en: "to his wife", sans: "स्वभार्यायै" },
{ en: "gave", sans: "दत्तवान्" },
{ en: "She", sans: "सा" },
{ en: "having eaten", sans: "खादित्वा" },
{ en: "very", sans: "अतीव" },
{ en: "happy", sans: "प्रसन्ना" },
{ en: "Then", sans: "तदा" },
{ en: "she", sans: "सा" },
{ en: "said", sans: "अवदत्" },
{ en: "if", sans: "यदि" },
{ en: "these", sans: "एतानि" },
{ en: "very sweet", sans: "अतिमधुराणि" },
{ en: "are", sans: "सन्ति" },
{ en: "then", sans: "तर्हि" },
{ en: "of the monkey", sans: "वानरस्य" },
{ en: "heart", sans: "हृदयं" },
{ en: "than that", sans: "ततोऽपि" },
{ en: "sweeter", sans: "मधुरं" },
{ en: "will be", sans: "भविष्यति" },
{ en: "again", sans: "पुनः" },
{ en: "you", sans: "त्वं" },
{ en: "the monkey", sans: "वानरं" },
{ en: "bring", sans: "आनय" },
{ en: "I", sans: "अहं" },
{ en: "his", sans: "तस्य" },
{ en: "to eat", sans: "खादितुम्" },
{ en: "wish", sans: "इच्छामि" },
{ en: "Wife's", sans: "भार्यायाः" },
{ en: "wish", sans: "इच्छां" },
{ en: "to fulfil", sans: "पूरयितुं" },
{ en: "though unwilling", sans: "अनिच्छन्नपि" },
{ en: "monkey's", sans: "वानरस्य" },
{ en: "near", sans: "समीपम्" },
{ en: "went", sans: "अगच्छत्" },
{ en: "my", sans: "मम" },
{ en: "wife", sans: "भार्या" },
{ en: "you", sans: "त्वां" },
{ en: "for a meal", sans: "भोजनार्थं" },
{ en: "invites", sans: "आमन्त्रयति" },
{ en: "come", sans: "आगच्छ" },
{ en: "in water", sans: "जलमध्ये" },
{ en: "how", sans: "कथं" },
{ en: "go", sans: "गच्छामि" },
{ en: "Crocodile", sans: "मकरः" },
{ en: "on my back", sans: "मम पृष्ठे" },
{ en: "sit", sans: "उपविश" },
{ en: "will take", sans: "नयामि" },
{ en: "on the crocodile's back", sans: "मकरस्य पृष्ठे" },
{ en: "sat", sans: "उपविष्टवान्" },
{ en: "They two", sans: "तौ" },
{ en: "in the middle of the river", sans: "नदीमध्ये" },
{ en: "went", sans: "अगच्छताम्" },
{ en: "truth", sans: "सत्यं" },
{ en: "said", sans: "उक्तवान्" },
{ en: "your", sans: "तव" },
{ en: "wants", sans: "इच्छति" },
{ en: "intelligent", sans: "बुद्धिमान्" },
{ en: "was", sans: "आसीत्" },
{ en: "alas", sans: "अहो" },
{ en: "on the tree", sans: "वृक्षे" },
{ en: "indeed, only", sans: "एव" },
{ en: "is", sans: "अस्ति" },
{ en: "me", sans: "मां" },
{ en: "of the tree", sans: "वृक्षस्य" },
{ en: "near", sans: "समीपं" },
{ en: "take", sans: "नयसि" },
{ en: "that", sans: "तत्" },
{ en: "give", sans: "ददामि" },
{ en: "having heard", sans: "श्रुत्वा" },
{ en: "monkey", sans: "वानरं" },
{ en: "near the tree", sans: "वृक्षस्य समीपं" },
{ en: "led", sans: "नीतवान्" },
{ en: "quickly", sans: "शीघ्रं" },
{ en: "tree", sans: "वृक्षम्" },
{ en: "climbed", sans: "आरूढवान्" },
{ en: "Then", sans: "ततः" },
{ en: "he", sans: "सः" },
{ en: "O fool", sans: "हे मूर्ख" },
{ en: "whose", sans: "कस्य" },
{ en: "outside the body", sans: "शरीरात् बहिः" },
{ en: "exists", sans: "भवति" },
{ en: "ashamed", sans: "लज्जितः" },
{ en: "however", sans: "तु" },
{ en: "by his own intelligence", sans: "स्वबुद्ध्या" },
{ en: "his life", sans: "स्वजीवनम्" },
{ en: "protected", sans: "अरक्षत्" },
{ en: "Therefore", sans: "अतः" },
{ en: "lesson", sans: "बोधः" },
{ en: "this", sans: "अयम्" },
{ en: "In danger", sans: "संकटे" },
{ en: "intelligence", sans: "बुद्धिः" },
{ en: "alone", sans: "एव" },
{ en: "protection", sans: "रक्षणं" },
{ en: "does", sans: "करोति" },
];
