const quizData = [
{ en: "Once", sans: "एकदा" },
{ en: "a, one", sans: "एकः" },
{ en: "hare", sans: "शशकः" },
{ en: "of his own", sans: "स्वस्य" },
{ en: "with running speed", sans: "धावनवेगेन" },
{ en: "pride, arrogance", sans: "गर्वं" },
{ en: "was doing", sans: "करोति स्म" },
{ en: "He", sans: "सः" },
{ en: "tortoise, turtle", sans: "कूर्मम्" },
{ en: "used to mock, laugh at", sans: "उपहसति स्म" },
{ en: "because", sans: "यतः" },
{ en: "very much, extremely", sans: "अतिशयेन" },
{ en: "slow-moving", sans: "मन्दगामी" },
{ en: "was", sans: "आसीत्" },
{ en: "Tortoise", sans: "कूर्मः" },
{ en: "calmly", sans: "शान्ततया" },
{ en: "replied", sans: "प्रत्यवदत्" },
{ en: "You", sans: "त्वं" },
{ en: "fast-moving", sans: "शीघ्रगामी" },
{ en: "are", sans: "भवसि" },
{ en: "but", sans: "किन्तु" },
{ en: "I", sans: "अहं" },
{ en: "in a competition, race", sans: "स्पर्धायां" },
{ en: "to defeat", sans: "पराजेतुं" },
{ en: "I can, I am able", sans: "शक्नोमि" },
{ en: "The hare", sans: "शशकः" },
{ en: "loudly", sans: "उच्चैः" },
{ en: "laughed", sans: "अहसत्" },
{ en: "This", sans: "एतद्" },
{ en: "impossible", sans: "अशक्यम्!" },
{ en: "still, nevertheless", sans: "तथापि" },
{ en: "your", sans: "तव" },
{ en: "challenge", sans: "आह्वानं" },
{ en: "accepted", sans: "स्वीकृतवान्" },
{ en: "I have", sans: "अस्मि" },
{ en: "Of the forest", sans: "वनस्य" },
{ en: "animals", sans: "पशवः" },
{ en: "race, competition", sans: "स्पर्धां" },
{ en: "to see, to watch", sans: "द्रष्टुं" },
{ en: "gathered, came together", sans: "समागताः" },
{ en: "One", sans: "एकः" },
{ en: "fox", sans: "लोमशः" },
{ en: "starting point", sans: "आरम्भबिन्दुं" },
{ en: "finishing point", sans: "समाप्तिबिन्दुं" },
{ en: "and", sans: "च" },
{ en: "marked", sans: "अचिह्नयत्" },
{ en: "When", sans: "यदा" },
{ en: "race", sans: "स्पर्धा" },
{ en: "began", sans: "आरब्धा" },
{ en: "then", sans: "तदा" },
{ en: "quickly, with speed", sans: "वेगेन" },
{ en: "ran", sans: "अधावत्" },
{ en: "much, far", sans: "बहु" },
{ en: "behind", sans: "पृष्ठे" },
{ en: "left behind", sans: "त्यक्तवान्" },
{ en: "A little", sans: "किञ्चित्" },
{ en: "distance", sans: "दूरं" },
{ en: "having run", sans: "धावित्वा" },
{ en: "backward, behind", sans: "पश्चात्" },
{ en: "looked", sans: "अपश्यत्" },
{ en: "slowly, gradually", sans: "शनैः शनैः" },
{ en: "going", sans: "गच्छन्तं" },
{ en: "saw", sans: "अद्राक्षीत्" },
{ en: "creature, animal", sans: "प्राणी" },
{ en: "me", sans: "मां" },
{ en: "ever", sans: "कदापि" },
{ en: "not", sans: "न" },
{ en: "will reach / will catch", sans: "प्राप्स्यति" },
{ en: "thus", sans: "इति" },
{ en: "thought", sans: "अचिन्तयत्" },
{ en: "With confidence", sans: "आत्मविश्वासेन" },
{ en: "full", sans: "पूर्णः" },
{ en: "of the tree", sans: "वृक्षस्य" },
{ en: "in the shade", sans: "छायायां" },
{ en: "for rest", sans: "विश्रामार्थं" },
{ en: "slept", sans: "सुप्तवान्" },
{ en: "at that time", sans: "तस्मिन् समये" },
{ en: "forward", sans: "अग्रे" },
{ en: "only", sans: "एव" },
{ en: "went", sans: "अगच्छत्" },
{ en: "one by one", sans: "एकैकं" },
{ en: "slowly", sans: "मन्दं" },
{ en: "steadily", sans: "स्थिरं" },
{ en: "step", sans: "पदं" },
{ en: "placed, put", sans: "न्यदधात्" },
{ en: "stopped", sans: "स्थितवान्" },
{ en: "just going", sans: "गच्छन् एव" },
{ en: "as long as, while", sans: "यावत्" },
{ en: "than that, from that", sans: "तस्मात्" },
{ en: "longer time", sans: "अधिककालं" },
{ en: "Finally, in the end", sans: "अन्ते" },
{ en: "awakened", sans: "प्रबुद्धः" },
{ en: "finish point", sans: "समाप्तिबिन्दुं" },
{ en: "towards", sans: "प्रति" },
{ en: "near him", sans: "तस्य समीपे" },
{ en: "having seen", sans: "दृष्ट्वा" },
{ en: "surprised", sans: "विस्मितः" },
{ en: "became", sans: "अभवत्" },
{ en: "suddenly", sans: "सहसा" },
{ en: "having stood up", sans: "उत्थाय" },
{ en: "as much as possible", sans: "यथाशक्ति" },
{ en: "very", sans: "अतीव" },
{ en: "delay", sans: "विलम्बः" },
{ en: "had happened", sans: "जातः आसीत्" },
{ en: "first", sans: "प्रथमः" },
{ en: "finish line", sans: "समाप्तिबिन्दुं" },
{ en: "reached", sans: "प्राप्तवान्" },
{ en: "of the tortoise", sans: "कूर्मस्य" },
{ en: "cheering, victory sound", sans: "जयध्वनिं" },
{ en: "made, did", sans: "कृतवन्तः" },
{ en: "with shame", sans: "लज्जया" },
{ en: "his head", sans: "स्वशिरः" },
{ en: "down", sans: "अधो" },
{ en: "lowered", sans: "नीतवान्" },
{ en: "with a smile", sans: "स्मितपूर्वकम्" },
{ en: "said", sans: "अवदत्" },
{ en: "even", sans: "अपि" },
{ en: "steady effort", sans: "स्थिरप्रयत्नः" },
{ en: "victory", sans: "विजयम्" },
{ en: "brings, leads to", sans: "आवहति" }
];
