const quizData = [
{ en: "Once", sans: "एकदा" },
{ en: "a, one", sans: "एकः" },
{ en: "hare, rabbit", sans: "शशकः" },
{ en: "of his own", sans: "स्वस्य" },
{ en: "with running speed", sans: "धावनवेगेन" },
{ en: "(garvaṃ) pride, arrogance", sans: "गर्वं" },
{ en: "was doing", sans: "करोति स्म" },
{ en: "He", sans: "सः" },
{ en: "tortoise, turtle", sans: "कूर्मम्" },
{ en: "used to mock, laugh at", sans: "उपहसति स्म" },
{ en: "because", sans: "यतः" },
{ en: "he", sans: "सः" },
{ en: "very much, extremely", sans: "अतिशयेन" },
{ en: "slow-moving", sans: "मन्दगामी" },
{ en: "was", sans: "आसीत्" },
{ en: "Tortoise", sans: "कूर्मः" },
{ en: "calmly", sans: "शान्ततया" },
{ en: "replied", sans: "प्रत्यवदत्" },
{ en: "You", sans: "त्वं" },
{ en: "fast-moving", sans: "शीघ्रगामी" },
{ en: "are", sans: "भवसि" },
{ en: "but", sans: "किन्तु" },
{ en: "I", sans: "अहं" },
{ en: "in a competition, race", sans: "स्पर्धायां" },
{ en: "you", sans: "त्वां" },
{ en: "to defeat", sans: "पराजयितुम्" },
{ en: "I can, I am able", sans: "शक्नोमि" },
{ en: "The hare", sans: "शशकः" },
{ en: "loudly", sans: "उच्चैः" },
{ en: "laughed", sans: "अहसत्" },
{ en: "This", sans: "एतद्" },
{ en: "impossible", sans: "अशक्यम्!" },
{ en: "Still, nevertheless", sans: "तथापि" },
{ en: "your", sans: "तव" },
{ en: "of the competition", sans: "स्पर्धायाः" },
{ en: "(āhvānaṃ) invitation", sans: "आह्वानं" },
{ en: "accepted", sans: "अङ्गीकरोमि" },
{ en: "Of the forest", sans: "वनस्य" },
{ en: "animals", sans: "पशवः" },
{ en: "(spardhāṃ) race, competition", sans: "स्पर्धां" },
{ en: "to see, to watch", sans: "द्रष्टुं" },
{ en: "gathered, came together", sans: "समागताः" },
{ en: "One", sans: "एकः" },
{ en: "fox", sans: "लोमशः" },
{ en: "starting point", sans: "आरम्भबिन्दुं" },
{ en: "finishing point", sans: "समाप्तिबिन्दुं" },
{ en: "and", sans: "च" },
{ en: "(acihnayat) marked", sans: "अचिह्नयत्" },
{ en: "When", sans: "यदा" },
{ en: "race", sans: "स्पर्धा" },
{ en: "began", sans: "आरब्धा" },
{ en: "then", sans: "तदा" },
{ en: "hare", sans: "शशकः" },
{ en: "quickly, with speed", sans: "वेगेन" },
{ en: "ran", sans: "अधावत्" },
{ en: "but", sans: "परन्तु" },
{ en: "(kūrmaṃ) tortoise", sans: "कूर्मं" },
{ en: "much, far", sans: "बहु" },
{ en: "behind", sans: "पृष्ठे" },
{ en: "A little", sans: "किञ्चित्" },
{ en: "distance", sans: "दूरं" },
{ en: "having run", sans: "धावित्वा" },
{ en: "behind", sans: "पृष्ठतः" },
{ en: "looked", sans: "अपश्यत्" },
{ en: "slowly", sans: "शनैः शनैः" },
{ en: "coming", sans: "आगच्छन्तं" },
{ en: "tortoise", sans: "कच्छपम्" },
{ en: "saw", sans: "अपश्यत्" },
{ en: "This", sans: "अयं" },
{ en: "slow moving", sans: "मन्दगामी" },
{ en: "animal", sans: "प्राणी" },
{ en: "me", sans: "मां" },
{ en: "ever", sans: "कदापि" },
{ en: "reach", sans: "प्राप्तुं" },
{ en: "cannot", sans: "(न) शक्नोति" },
{ en: "thus", sans: "इति" },
{ en: "thought", sans: "अचिन्तयत्" },
{ en: "With confidence", sans: "आत्मविश्वासेन" },
{ en: "full", sans: "पूर्णः" },
{ en: "of the tree", sans: "वृक्षस्य" },
{ en: "in the shade", sans: "छायायां" },
{ en: "(viśrāmārthaṃ) for rest", sans: "विश्रामार्थं" },
{ en: "slept", sans: "सुप्तवान्" },
{ en: "Meanwhile", sans: "तावत्" },
{ en: "tortoise", sans: "कच्छपः" },
{ en: "one by one", sans: "एकैकं" },
{ en: "slowly", sans: "मन्दं" },
{ en: "steadily", sans: "स्थिरं" },
{ en: "step", sans: "पदं" },
{ en: "having placed", sans: "अस्थाप्य" },
{ en: "forward", sans: "अग्रे" },
{ en: "to go", sans: "गन्तुम्" },
{ en: "continued", sans: "अनुवर्तत" },
{ en: "(viśrāmārtham) to rest", sans: "विश्रामार्थं" },
{ en: "not", sans: "न" },
{ en: "stop", sans: "अतिष्ठत्" },
{ en: "continuously", sans: "निरन्तरं" },
{ en: "moved forward", sans: "पुरोधावत्" },
{ en: "Hare", sans: "शशकः" },
{ en: "as long as", sans: "यावत्कालं" },
{ en: "to sleep", sans: "निद्रातुम्" },
{ en: "wished", sans: "ऐच्छत्" },
{ en: "than", sans: "तस्मात्" },
{ en: "more", sans: "अधिकं" },
{ en: "finally, in the end", sans: "अन्ततः" },
{ en: "woke up", sans: "उत्थितवान्" },
{ en: "finish line", sans: "समाप्तिरेखां" },
{ en: "towards", sans: "प्रति" },
{ en: "There", sans: "तत्र" },
{ en: "almost", sans: "प्रायः" },
{ en: "reached", sans: "प्राप्तं" },
{ en: "having seen", sans: "दृष्ट्वा" },
{ en: "very", sans: "अत्यन्तं" },
{ en: "surprised", sans: "विस्मितः" },
{ en: "became", sans: "अभवत्" },
{ en: "suddenly", sans: "सहसा" },
{ en: "having stood up", sans: "उत्थाय" },
{ en: "as much as possible", sans: "यथाशक्ति" },
{ en: "But", sans: "किन्तु" },
{ en: "very", sans: "अतीव" },
{ en: "late", sans: "विलम्बः" },
{ en: "had happened", sans: "जातः आसीत्" },
{ en: "first", sans: "प्रथमम् एव" },
{ en: "finish line", sans: "समाप्तिरेखाम्" },
{ en: "reached", sans: "अतिक्रान्तवान्" },
{ en: "had", sans: "आसीत्" },
{ en: "Animals", sans: "जन्तवः" },
{ en: "of the tortoise", sans: "कूर्मस्य" },
{ en: "cheering, victory sound", sans: "जयघोषं" },
{ en: "made, did", sans: "कृतवन्तः" },
{ en: "ashamed", sans: "लज्जितः" },
{ en: "being", sans: "सन्" },
{ en: "his head", sans: "स्वशिरम्" },
{ en: "hung down", sans: "अधः कृतवान्" },
{ en: "with a smile", sans: "मन्दहासेन" },
{ en: "said", sans: "उक्तवान्" },
{ en: "slow", sans: "मन्दं" },
{ en: "steady", sans: "स्थिरं" },
{ en: "movement", sans: "गमनं" },
{ en: "wins", sans: "जयति" },
{ en: "race", sans: "स्पर्धाम्" },
];
