const quizData = [
    { en: "above, below", sans: "उपरि, अधः" },
    { en: "absence, presence", sans: "अनुपस्थितिः, उपस्थितिः" },
    { en: "abundant, scarce", sans: "प्रभूत, अल्प" },
    { en: "accept, reject", sans: "अङ्गीकरोति, तिरस्करोति" },
    { en: "accidentally, intentionally", sans: "अकस्मात्, जानपूर्वकम्" },
    { en: "accurate, inaccurate", sans: "यथार्थ, अयथार्थ" },
    { en: "adds, subtracts", sans: "योजयति, वियोजयति" },
    { en: "advanced, elementary", sans: "उन्नत, प्रारम्भिक" },
    { en: "advantage, disadvantage", sans: "लाभः, हानिः" },
    { en: "agree, disagree", sans: "स्वीकरोति, अस्वीकरोति" },
    { en: "all, none", sans: "सर्वम्, न किमपि" },
    { en: "allow, forbid", sans: "अनुज्ञायते, निषेधति" },
    { en: "always, never", sans: "सर्वदा, कदापि न" },
    { en: "amateur, professional", sans: "आरम्भकः, प्रवीणः" },
    { en: "amuse, bore", sans: "मनोरञ्जयति, उद्वेजयति" },
    { en: "ancestor, descendant", sans: "पूर्वजः, वंशजः" },
    { en: "ancient, modern", sans: "प्राचीनः, आधुनिकः" },
    { en: "angel, devil", sans: "देवदूतः, असुरः" },
    { en: "animal, human", sans: "पशुः, मानवः" },
    { en: "annoys, consoles", sans: "क्रोधयति, आश्वासयति" },
    { en: "appeared, disappeared", sans: "आविर्भूतः, तिरोभूतः" },
    { en: "approves, disapproves", sans: "अनुमोदयति, अननुमोदयति" },
    { en: "approximately, exactly", sans: "प्रायः, सटीकतः" },
    { en: "arrives, departs", sans: "प्राप्नोति, निर्गच्छति" },
    { en: "ascends, descends", sans: "आरोहति, अवरोहति" },
    { en: "asks, replies", sans: "पृच्छति, प्रतिवदति" },
    { en: "attacks, defends", sans: "आक्रमति, संरक्षति" },
    { en: "attractive, repulsive", sans: "आकर्षक, बीभत्स" },
    { en: "audible, inaudible", sans: "श्रव्य, अश्रव्य" },
    { en: "autumn, spring", sans: "शरद्ऋतुः, वसन्तऋतुः" },
    { en: "awake, asleep", sans: "जागृतः, सुप्तः" },
    { en: "in front, behind", sans: "पुरतः, पृष्ठतः" },
    { en: "forward (direction), backward (direction)", sans: "अग्रे, पश्चात्" },
    { en: "beautiful, ugly", sans: "सुन्दर, कुरूप" },
    { en: "before, after", sans: "पूर्वम्, पश्चात्" },
    { en: "begins, ends", sans: "आरभते, समापयति" },
    { en: "beginning, ending", sans: "आदिः, अन्तः" },
    { en: "best, worst", sans: "उत्तम, अधम" },
    { en: "better, worse", sans: "श्रेयतर, हीनतर" },
    { en: "big, small", sans: "बृहत्, लघु" },
    { en: "black, white", sans: "कृष्ण, श्वेत" },
    { en: "blames, praises", sans: "निन्दति, श्लाघते" },
    { en: "blesses, curses", sans: "आशीर्वादं ददाति, शापम् ददाति" },
    { en: "blunt, sharp", sans: "अतीक्ष्ण, तीक्ष्ण" },
    { en: "body, soul", sans: "शरीरम्, आत्मा" },
    { en: "bold, meek", sans: "धीर, भीरु" },
    { en: "boring, exciting", sans: "नीरस, रोमाञ्चकर" },
    { en: "borrow, lend", sans: "ऋणं गृह्णाति, ऋणं ददाति" },
    { en: "boy, girl", sans: "बालकः, बालिका" },
    { en: "brings, sends", sans: "आनयति, प्रेषयति" },
    { en: "Brother, Sister", sans: "सहोदरः, सहोदरी" },
    { en: "builds, destroys", sans: "निर्माति, विनाशयति" },
    { en: "buys, sells", sans: "क्रीणाति, विक्रयणं करोति" },
    { en: "calm, excited", sans: "शान्तः, उत्सुकः" },
    { en: "can (able to), cannot (unable to)", sans: "शक्नोति, न शक्नोति" },
    { en: "can be done, cannot be done", sans: "शक्यते, न शक्यते" },
    { en: "careful, careless", sans: "सावधान, असावधान" },
    { en: "catch, drop", sans: "गृह्णाति, पातयति" },
    { en: "chaos, order", sans: "अस्तव्यस्तता, व्यवस्था" },
    { en: "cheap, expensive", sans: "अल्पमूल्य, बहुमूल्य" },
    { en: "cheerful, sad", sans: "आनन्दित, दुःखित" },
    { en: "child, adult", sans: "बालः, प्रौढः" },
    { en: "children, parents", sans: "बालाः, मातापितरौ" },
    { en: "clockwise, counterclockwise", sans: "प्रदक्षिणम्, अप्रदक्षिणम्" },
    { en: "cloudy, clear", sans: "मेघयुक्तः, निर्मलः" },
    { en: "comfort, discomfort", sans: "सुखम्, असुखम्" },
    { en: "compliment, insult", sans: "प्रशंसा, निन्दा" },
    { en: "compulsory, voluntary", sans: "आवश्यक, ऐच्छिक" },
    { en: "hides, shows", sans: "गोपयति, प्रकटयति" },
    { en: "consonant, vowel", sans: "व्यञ्जनम्, स्वरः" },
    { en: "constant, variable", sans: "नित्य, परिवर्तनशील" },
    { en: "construction, destruction", sans: "निर्माणम्, संहारम्" },
    { en: "continues, stops", sans: "अनुवर्तते, विरमति" },
    { en: "convenient, inconvenient", sans: "अनुकूल, प्रतिकूल" },
    { en: "cooked, uncooked", sans: "पक्व, अपक्व" },
    { en: "cool, warm", sans: "शीतलम्, उष्णम्" },
    { en: "courage, fear", sans: "धैर्यम्, भयम्" },
    { en: "brave, coward", sans: "धीरः, भीरुः" },
    { en: "confident, timid", sans: "धृष्टः, कातरः" },
    { en: "creates, destroys", sans: "संसृजति, संहरति" },
    { en: "daughter, son", sans: "पुत्री, पुत्रः" },
    { en: "day, night", sans: "दिनम्, रात्रिः" },
    { en: "daytime, nighttime", sans: "दिवा, निशा" },
    { en: "dead, alive", sans: "मृत, जीवित" },
    { en: "death, birth", sans: "मरणम्, जन्म" },
    { en: "definite, indefinite", sans: "निश्चित, अनिश्चित" },
    { en: "demand, supply", sans: "मागः, पूर्ति" },
    { en: "despair, hope", sans: "निराशा, आशा" },
    { en: "dim, bright", sans: "म्लान, उज्ज्वल" },
    { en: "dirty, clean", sans: "मलिन, स्वच्छ" },
    { en: "Doctor, patient", sans: "वैद्यः, रोगी" },
    { en: "downwards, upwards", sans: "अधस्तात्, ऊर्ध्वम्" },
    { en: "dry, wet", sans: "शुष्क, आर्द्र" },
    { en: "early, late", sans: "पूर्वम्, विलम्बितः" },
    { en: "east, west", sans: "पूर्व, पश्चिम" },
    { en: "easy, Difficult", sans: "सरल, कठिन" },
    { en: "encourage, discourage", sans: "प्रोत्साहयति, निरुत्साहयति" },
    { en: "enjoys, hates", sans: "रोचते, न रोचते" },
    { en: "enters, exits", sans: "प्रविशति, निर्गच्छति" },
    { en: "entrance, exit", sans: "प्रवेश, निर्गम" },
    { en: "expands, contracts", sans: "विस्तृणोति, सङ्कुचितं भवति" },
    { en: "external, internal", sans: "बाह्य, अभ्यन्तर" },
    { en: "fail, pass", sans: "अनुत्तीर्ण, उत्तीर्ण" },
    { en: "far, near", sans: "दूर, समीप" },
    { en: "favourable, unfavourable", sans: "अनुकूल, प्रतिकूल" },
    { en: "find, lose", sans: "प्राप्नोति, नष्ट" },
    { en: "first, last", sans: "प्रथम, अन्तिम" },
    { en: "fixes, breaks", sans: "स्थिरी करोति, भग्नं करोति" },
    { en: "flat, hilly", sans: "समतल, पर्वतीय" },
    { en: "floor, ceiling", sans: "कुट्टिमम्, उपरितलम्" },
    { en: "folds, unfolds", sans: "पुटी करोति, विस्तारयति" },
    { en: "follows, leads", sans: "अनुसरति, नयति" },
    { en: "for, against", sans: "कृते, विरुद्धम्" },
    { en: "foreground, background", sans: "अग्रभूमिका, पृष्ठभूमिका" },
    { en: "foreign, domestic", sans: "विदेशीय, स्वदेशीय" },
    { en: "fortunate, unfortunate", sans: "सुभाग्यवान्, दुर्भाग्य" },
    { en: "free, bound", sans: "मुक्तः, बद्धः" },
    { en: "frequently, occasionally", sans: "बहुवारम्, कदाचित्" },
    { en: "fresh, stale", sans: "अभिनव, पर्युषित" },
    { en: "friend, enemy", sans: "मित्रम्, शत्रुः" },
    { en: "from here, from there", sans: "इतः, ततः" },
    { en: "front, rear", sans: "पुरतः, पृष्ठतः" },
    { en: "Full, Empty", sans: "पूर्ण, रिक्त" },
    { en: "generous, stingy", sans: "उदार, कृपण" },
    { en: "gentle, rough", sans: "कोमल, परुष" },
    { en: "giant, dwarf", sans: "महाकायः, वामनः" },
    { en: "gives, takes", sans: "ददाति, स्वीकरोति" },
    { en: "goes, comes", sans: "गच्छति, आगच्छति" },
    { en: "good luck, bad luck", sans: "सौभाग्यम्, दौर्भाग्यम्" },
    { en: "good, bad", sans: "शुभम्, अशुभम्" },
    { en: "guest, host", sans: "अतिथिः, आतिथेयः" },
    { en: "guilty, innocent", sans: "अपराधी, निरपराधी" },
    { en: "happiness, sadness", sans: "सुखम्, दुःखम्" },
    { en: "happy, sad", sans: "सुखी, दुःखी" },
    { en: "easy, hard (difficult)", sans: "सरल, कठिन" },
    { en: "soft, hard (firm)", sans: "मृदु, कठोर" },
    { en: "harmful, harmless", sans: "हानिकारक, अहानिकारक" },
    { en: "health, disease", sans: "स्वास्थ्यम्, रोगः" },
    { en: "healthy, unhealthy", sans: "स्वस्थ, अस्वस्थ" },
    { en: "heaven, hell", sans: "स्वर्गम्, नरकम्" },
    { en: "here, there", sans: "अत्र, तत्र" },
    { en: "hero, coward", sans: "शूरः, भीरुः" },
    { en: "helps, hinders", sans: "उपकरोति, अपकरोति" },
    { en: "honest, dishonest", sans: "निष्कपट, कपटयुक्त" },
    { en: "honor, dishonor", sans: "सम्मानः, अवमानः" },
    { en: "hopeful, desperate", sans: "आशायुक्त, आशाहीन" },
    { en: "horizontal, vertical", sans: "तिर्यक्, ऊर्ध्व" },
    { en: "Hot, Cold", sans: "उष्ण, शीत" },
    { en: "humble, arrogant", sans: "नम्र, सदर्प" },
    { en: "hungry, satiated", sans: "बुभुक्षित, तृप्त" },
    { en: "Husband, Wife", sans: "पतिः, पत्नी" },
    { en: "import, export", sans: "आयातः, निर्यातः" },
    { en: "important, trivial", sans: "मुख्य, तुच्छ" },
    { en: "in, out", sans: "अन्तः, बहिः" },
    { en: "include, exclude", sans: "अन्तर्भावयति, वर्जयति" },
    { en: "increase, decrease", sans: "वृद्धिः, ह्रासः" },
    { en: "inhalation, exhalation", sans: "पूरकः, रेचकः" },
    { en: "inner, outer", sans: "आभ्यन्तर, बहिःस्थ" },
    { en: "interesting, boring", sans: "रोचकम्, नीरसम्" },
    { en: "interior, exterior", sans: "आन्तर, बाह्य" },
    { en: "junior, senior", sans: "कनीयान्, ज्येष्ठ" },
    { en: "justice, injustice", sans: "न्याय, अन्याय" },
    { en: "kind, cruel", sans: "दयालु, क्रूर" },
    { en: "knowledge, ignorance", sans: "विद्या, अविद्या" },
    { en: "known, unknown", sans: "ज्ञात, अज्ञात" },
    { en: "landlord, tenant", sans: "भूस्वामी, भाटकः" },
    { en: "laughs, cries", sans: "हसति, रोदिति" },
    { en: "lawful, illegal", sans: "धर्म्य, अधर्म्य" },
    { en: "lazy, active", sans: "अलस, सक्रिय" },
    { en: "leader, follower", sans: "नायकः, अनुचरः" },
    { en: "learns, teaches", sans: "पठति, पाठयति" },
    { en: "lies down, stands up", sans: "शयनं करोति, उत्तिष्ठति" },
    { en: "light (weight), heavy", sans: "लघु, गुरु" },
    { en: "light (color), dark (color)", sans: "हल्कवर्ण, कृष्णवर्ण" },
    { en: "bright (brightness), dark", sans: "दीप्त, तमसः" },
    { en: "likes, dislikes", sans: "इच्छति, न इच्छति" },
    { en: "likely, unlikely", sans: "सम्भाव्य, असम्भाव्य" },
    { en: "limited, unlimited", sans: "मित, अमित" },
    { en: "liquid, solid", sans: "द्रवः, घनः" },
    { en: "loser, winner", sans: "पराजितः, विजेता" },
    { en: "love, hate", sans: "प्रेम, द्वेष" },
    { en: "lovely, terrible", sans: "सुन्दर, भयङ्कर" },
    { en: "low, high", sans: "निम्न, उच्च" },
    { en: "loyal, disloyal", sans: "निष्ठावान्, निष्ठाहीन" },
    { en: "major, minor", sans: "प्रधान, अप्रधान" },
    { en: "male, female", sans: "नरः, नारी" },
    { en: "man, woman", sans: "पुरुषः, स्त्री" },
    { en: "many, few", sans: "बहवः, अल्पाः" },
    { en: "married, divorced", sans: "विवाहित, विच्छिन्नविवाहः" },
    { en: "melts, freezes", sans: "द्रवति, हिमीयते" },
    { en: "minimum, maximum", sans: "न्यूनतम, अधिकतम" },
    { en: "miss, hit", sans: "लक्ष्यभ्रष्टः, प्रहरति" },
    { en: "moderate, extreme", sans: "सन्तुलित, अतिशय" },
    { en: "more, less", sans: "अधिकम्, न्यूनम्" },
    { en: "morning, evening", sans: "प्रातः, सायम्" },
    { en: "mountain, valley", sans: "पर्वतः, उपत्यका" },
    { en: "multiplies, divides", sans: "गुणयति, विभजति" },
    { en: "natural, artificial", sans: "प्राकृतिक, कृत्रिम" },
    { en: "neat, messy", sans: "सुव्यवस्थित, अव्यवस्थित" },
    { en: "nice, awful", sans: "सुष्ठु, भयंकर" },
    { en: "niece (brother's daughter), niece (sister's daughter)", sans: "भ्रातृजा, भागिनेयी" },
    { en: "nephew (brother's son), nephew (sister's son)", sans: "भ्रातृजः, भागिनेयः" },
    { en: "noble, wicked", sans: "साधु, दुष्ट" },
    { en: "nobody, everybody", sans: "न कोऽपि, सर्वे जनाः" },
    { en: "noon, midnight", sans: "मध्याह्नः, मध्यरात्रिः" },
    { en: "north, south", sans: "उत्तर, दक्षिण" },
    { en: "not yet, already", sans: "अद्यापि न, पूर्वम् एव" },
    { en: "nothing, everything", sans: "न किमपि, सर्वम्" },
    { en: "notices, ignores", sans: "लक्षयति, न लक्षयति" },
    { en: "now, later", sans: "इदानीम्, अनन्तरं" },
    { en: "obedient, disobedient", sans: "आज्ञाकारः, आज्ञाभङ्गकरः" },
    { en: "odd, even", sans: "विषमसङ्ख्या, समसंख्या" },
    { en: "often, seldom", sans: "बहुवारम्, कदाचित्" },
    { en: "old, new", sans: "पुरातन, नूतन" },
    { en: "old (age), young (age)", sans: "वृद्धः, युवकः" },
    { en: "modern", sans: "आधुनिक" },
    { en: "one, many", sans: "एक, अनेक" },
    { en: "opens, closes", sans: "उद्घाटयति, पिधानं करोति" },
    { en: "opposes, supports", sans: "विरोधं करोति, समर्थनं करोति" },
    { en: "optimist, pessimist", sans: "आशावादी, निराशावादी" },
    { en: "ordinary, special", sans: "साधारण, विशेष" },
    { en: "outskirts (of city), centre (of city)", sans: "नगरप्रान्त, नगरमध्यः" },
    { en: "over, under", sans: "उपरि, अधः" },
    { en: "partial, total", sans: "आंशिक, पूर्ण" },
    { en: "particular, general", sans: "विशेष, सामान्य" },
    { en: "past, future", sans: "भूतकालः, भविष्यत्कालः" },
    { en: "patient, impatient", sans: "सहनशील, असहनशील" },
    { en: "peaceful, violent", sans: "शान्त, उग्र" },
    { en: "permanent, temporary", sans: "स्थायी, अस्थायी" },
    { en: "plants, harvests", sans: "रोपयति, लुनाति" },
    { en: "poor, rich", sans: "दरिद्र, धनिक" },
    { en: "possible, impossible", sans: "साध्य, असाध्य" },
    { en: "present, absent", sans: "उपस्थित, अनुपस्थित" },
    { en: "present (time), past (time)", sans: "वर्तमानकालः, भूतकालः" },
    { en: "probably, certainly", sans: "सम्भाव्यतः, निश्चयेन" },
    { en: "prudent, imprudent", sans: "विमृश्यकारी, अविमृश्यकारी" },
    { en: "public, private", sans: "सार्वजनिक, वैयक्तिक" },
    { en: "pure, impure", sans: "शुद्ध, अशुद्ध" },
    { en: "pushes, pulls", sans: "नुदति, आकर्षति" },
    { en: "qualified, unqualified", sans: "समर्थ, असमर्थ" },
    { en: "question, answer", sans: "प्रश्नः, उत्तरम्" },
    { en: "quiet, noisy", sans: "शान्त, कोलाहलपूर्ण" },
    { en: "raises, lowers", sans: "उत्थापयति, अवनयति" },
    { en: "rarely, common", sans: "कदाचित्, सामान्य" },
    { en: "real, unreal", sans: "वास्तविक, मिथ्या" },
    { en: "receives, gives", sans: "स्वीकरोति, ददाति" },
    { en: "regular, irregular", sans: "नियत, अनियत" },
    { en: "remembers, forgets", sans: "स्मरति, विस्मरति" },
    { en: "repair, damage", sans: "मरम्मतं करोति, हानि" },
    { en: "rests, works", sans: "विश्रामं करोति, परिश्रमं करोति" },
    { en: "right (direction), left (direction)", sans: "दक्षिणपार्श्वम्, वामपार्श्वम्" },
    { en: "right, wrong", sans: "सम्यक्, असम्यक्" },
    { en: "proper, improper", sans: "उचित, अनुचित" },
    { en: "rough, smooth", sans: "परुष, मृदु" },
    { en: "rude, polite", sans: "कठोर, सभ्य" },
    { en: "safe, dangerous", sans: "सुरक्षित, अपायकर" },
    { en: "salt, sugar", sans: "लवणम्, शर्करा" },
    { en: "same, opposite", sans: "समान, विपरीत" },
    { en: "same, different", sans: "समान, भिन्न" },
    { en: "satisfactory, unsatisfactory", sans: "सन्तोषदायक, असन्तोषदायक" },
    { en: "saves (protects), destroys", sans: "रक्षति, नाशयति" },
    { en: "saves (money), spends", sans: "सञ्चयम् करोति, व्ययं करोति" },
    { en: "secure, insecure", sans: "सुरक्षित, असुरक्षित" },
    { en: "separates, joins", sans: "पृथक् करोति, संयोजयति" },
    { en: "serious, funny", sans: "गम्भीरः, विनोदी" },
    { en: "servant, master", sans: "सेवकः, स्वामी" },
    { en: "sets free, arrests", sans: "विमोचयति, गृहीत्वा बध्नाति" },
    { en: "shallow, deep", sans: "गाधः, अगाधः" },
    { en: "short (height), tall (height)", sans: "ह्रस्वकाय, उन्नतकाय" },
    { en: "short (length), long (length)", sans: "ह्रस्व, दीर्घ" },
    { en: "shouts, whispers", sans: "आक्रोशति, मन्दस्वरे वदति" },
    { en: "shows, hides", sans: "दर्शयति, गोपयति" },
    { en: "shrinks, grows", sans: "सङ्कुचति, वर्धति" },
    { en: "sick, healthy", sans: "अस्वस्थ, स्वस्थ" },
    { en: "simple, complex", sans: "सरल, जटिल" },
    { en: "singular, plural", sans: "एकवचनम्, बहुवचनम्" },
    { en: "sinks, floats", sans: "निमज्जति, प्लवते" },
    { en: "slow, fast", sans: "मन्दम्, शीघ्रम्" },
    { en: "sober, drunk", sans: "संयमी, मत्त" },
    { en: "somewhere, nowhere", sans: "कुत्रापि, न कुत्रापि" },
    { en: "sorrow, joy", sans: "विषादः, आनन्दः" },
    { en: "stands, sits", sans: "तिष्ठति, उपविशति" },
    { en: "start, finish", sans: "आरम्भः, समाप्तिः" },
    { en: "starts, stops", sans: "आरभते, विरमति" },
    { en: "straight, bent", sans: "ऋजु, वक्र" },
    { en: "strange, normal", sans: "विचित्र, सामान्य" },
    { en: "stranger, acquaintance", sans: "अपरिचितः, परिचितः" },
    { en: "strict, lenient", sans: "कठोर, उदार" },
    { en: "strong (person), weak (person)", sans: "बलवान्, दुर्बल" },
    { en: "student, teacher", sans: "छात्रः, अध्यापकः" },
    { en: "stupid, intelligent", sans: "मूर्ख, बुद्धिमान्" },
    { en: "subtle, gross", sans: "सूक्ष्म, स्थूल" },
    { en: "success, failure", sans: "सफलता, असफलता" },
    { en: "summer, winter", sans: "ग्रीष्मकालः, शीतकालः" },
    { en: "sun, moon", sans: "सूर्यः, चन्द्रः" },
    { en: "sunny, cloudy", sans: "सूर्यप्रकाशित, मेघाच्छन्न" },
    { en: "sunrise, sunset", sans: "सूर्योदयः, सूर्यास्तः" },
    { en: "dawn, dusk", sans: "प्रातःकालः, सन्ध्या" },
    { en: "sweet, bitter", sans: "मधुरः, तिक्तः" },
    { en: "sour, astringent", sans: "अम्लः, कषायः" },
    { en: "salty, spicy", sans: "लवणम्, कटुकः" },
    { en: "thin, fat", sans: "कृश, स्थूल" },
    { en: "thirsty, quenched", sans: "पिपासित, तृप्त" },
    { en: "tight, loose", sans: "दृढ, शिथिल" },
    { en: "tired, relaxed", sans: "श्रान्त, विश्रान्त" },
    { en: "tiny, huge", sans: "लघु, बृहत्" },
    { en: "together, apart", sans: "मिलित्वा, पृथक्" },
    { en: "top, bottom", sans: "उपरितन, तलम्" },
    { en: "tough, easy", sans: "कठिन, सुलभ" },
    { en: "transparent, opaque", sans: "पारदर्शक, अपारदर्शक" },
    { en: "true, false", sans: "सत्य, असत्य" },
    { en: "trust, mistrust", sans: "विश्वासः, अविश्वासः" },
    { en: "truth, falsehood", sans: "सत्यम्, मिथ्यात्वम्" },
    { en: "understands, misunderstands", sans: "अवगच्छति, मिथ्यावगच्छति" },
    { en: "unites, divides", sans: "सङ्घटयति, विभजति" },
    { en: "unity, diversity", sans: "एकता, अनेकता" },
    { en: "up, down", sans: "उपरि, अधः" },
    { en: "upstairs, downstairs", sans: "उपरितनतल, अधस्तनतल" },
    { en: "us, them", sans: "वयम्, ते" },
    { en: "useful, useless", sans: "उपयुक्त, अनुपयुक्त" },
    { en: "vacant, occupied", sans: "रिक्त, आवृत्त" },
    { en: "victory, defeat", sans: "जयः, पराजयः" },
    { en: "village, town", sans: "ग्रामः, नगरम्" },
    { en: "virtue, vice", sans: "धर्मः, अधर्मः" },
    { en: "visible, invisible", sans: "व्यक्त, अव्यक्त" },
    { en: "war, peace", sans: "युद्धम्, शान्तिः" },
    { en: "wealth, poverty", sans: "सम्पत्तिः, दारिद्र्यम्" },
    { en: "whole, part", sans: "सम्पूर्ण, भागः" },
    { en: "wide, narrow", sans: "विस्तृत, सङ्कीर्ण" },
    { en: "wins, loses", sans: "जयति, पराजयति" },
    { en: "wisdom, stupidity", sans: "विवेकम्, मूढता" },
    { en: "wise, foolish", sans: "विवेकी, मूर्खः" },
    { en: "yes, no", sans: "आम्, न" },
];
