const quizData = [
    { en: "above, below", sans: "उपरि, अधः" },
    { en: "absence, presence", sans: "अनुपस्थितिः, उपस्थितिः" },
    { en: "abundant, scarce", sans: "प्रभूत, अल्प" },
    { en: "accept, reject", sans: "अङ्गीकरोति, तिरस्करोति" },
    { en: "accidentally, intentionally", sans: "अकस्मात्, जानपूर्वकम्" },
    { en: "accurate, inaccurate", sans: "यथार्थ, अयथार्थ" },
    { en: "adds, subtracts", sans: "योजयति, वियोजयति" },
    { en: "advanced, elementary", sans: "उन्नत, प्रारम्भिक" },
    { en: "advantage, disadvantage", sans: "लाभः, हानिः" },
    { en: "agree, disagree", sans: "स्वीकरोति, अस्वीकरोति" },
    { en: "all, none", sans: "सर्वम्, न किमपि" },
    { en: "allow, forbid", sans: "अनुज्ञायते, निषेधति" },
    { en: "always, never", sans: "सर्वदा, कदापि न" },

    /***** */

    { en: "amateur", sans: "आरम्भकः" },
    { en: "professional", sans: "प्रवीणः" },
    { en: "amuse", sans: "मनोरञ्जनम्" },
    { en: "bore", sans: "जामिता" },
    { en: "ancestor", sans: "पूर्वजः" },
    { en: "descendant", sans: "प्रजा" },
    { en: "ancient", sans: "प्राचीनः" },
    { en: "modern", sans: "नवीनः" },
    { en: "angel", sans: "देवदूतः" },
    { en: "devil", sans: "पिशाची" },
    { en: "animal", sans: "पशुः" },
    { en: "human", sans: "नरः" },
    { en: "annoys", sans: "रुशति" },
    { en: "consoles", sans: "आश्वासयति" },
    { en: "appeared", sans: "आविर्भूतः" },
    { en: "disappeared", sans: "अदृश्यः" },
    { en: "approves", sans: "अनुमोदयति" },
    { en: "disapproves", sans: "निराकरोति" },
    { en: "approximately", sans: "प्रायः" },
    { en: "exactly", sans: "यथावत्" },
    { en: "arrives", sans: "प्राप्नोति" },
    { en: "departs", sans: "निर्गच्छति" },
    { en: "ascends", sans: "आरोहति" },
    { en: "descends", sans: "अवरोहति" },
    { en: "asks", sans: "पृच्छति" },
    { en: "replies", sans: "प्रतिवदति" },
    { en: "attacks", sans: "आक्रमणम् करोति" },
    { en: "defends", sans: "संरक्षति" },
    { en: "attractive", sans: "आकर्षक" },
    { en: "repulsive", sans: "बीभत्स" },
    { en: "audible", sans: "स्फुट" },
    { en: "inaudible", sans: "अस्फुट" },
    { en: "autumn", sans: "शरद्ऋतुः" },
    { en: "spring", sans: "वसन्तऋतुः" },
    { en: "awake", sans: "जागृतः" },
    { en: "asleep", sans: "सुप्तः" },
    { en: "in front", sans: "पुरतः" },
    { en: "behind", sans: "पृष्ठतः" },
    { en: "forward (direction)", sans: "अग्रे" },
    { en: "backward (direction)", sans: "पश्चात्" },
    { en: "beautiful", sans: "सुन्दर" },
    { en: "ugly", sans: "कुरूप" },
    { en: "Before", sans: "पूर्वम्" },
    { en: "after", sans: "परम्" },
    { en: "begins", sans: "आरम्भः भवति" },
    { en: "ends", sans: "समापनं भवति" },
    { en: "beginning", sans: "आदिः" },
    { en: "ending", sans: "अन्तः" },
    { en: "best", sans: "उत्तम" },
    { en: "worst", sans: "अधम" },
    { en: "better", sans: "समीचीनतर" },
    { en: "worse", sans: "हीनतर" },
    { en: "big", sans: "बृहत्" },
    { en: "small", sans: "लघु" },
    { en: "black", sans: "कृष्ण" },
    { en: "white", sans: "श्वेत" },
    { en: "blames", sans: "निन्दति" },
    { en: "praises", sans: "श्लाघते" },
    { en: "blesses", sans: "आशीर्वादं ददाति" },
    { en: "curses", sans: "शापम् ददाति" },
    { en: "blunt", sans: "अतीक्ष्ण" },
    { en: "sharp", sans: "तीक्ष्ण" },
    { en: "body", sans: "शरीरम्" },
    { en: "soul", sans: "आत्मा" },
    { en: "bold", sans: "धीर" },
    { en: "meek", sans: "अधीर" },
    { en: "boring", sans: "नीरस" },
    { en: "exciting", sans: "रोमाञ्चकर" },
    { en: "borrow", sans: "ऋणग्रहणम्" },
    { en: "lend", sans: "ऋणदानम्" },
    { en: "boy", sans: "बालकः" },
    { en: "girl", sans: "बालिका" },
    { en: "brings", sans: "आनयति" },
    { en: "sends", sans: "प्रेषयति" },
    { en: "Brother", sans: "सहोदरः" },
    { en: "Sister", sans: "सहोदरी" },
    { en: "builds", sans: "निर्माति" },
    { en: "destroys", sans: "विनाशयति" },
    { en: "buys", sans: "क्रीणाति" },
    { en: "sells", sans: "विक्रयणं करोति" },
    { en: "calm", sans: "शान्तः" },
    { en: "excited", sans: "उत्सुकः" },
    { en: "can (able to)", sans: "शक्नोति" },
    { en: "cannot (unable to)", sans: "न शक्नोति" },
    { en: "can be done", sans: "शक्यते" },
    { en: "cannot be done", sans: "न शक्यते" },
    { en: "careful", sans: "सावधान" },
    { en: "careless", sans: "असावधान" },
    { en: "catch", sans: "ग्रहणम्" },
    { en: "drop", sans: "पातितम्" },
    { en: "chaos", sans: "अस्तव्यस्तता" },
    { en: "order", sans: "व्यवस्था" },
    { en: "cheap", sans: "अल्पमूल्य" },
    { en: "expensive", sans: "बहुमूल्य" },
    { en: "cheerful", sans: "आनन्दित" },
    { en: "sad", sans: "दुःखित" },
    { en: "child", sans: "बालः" },
    { en: "adult", sans: "प्रौढः" },
    { en: "children", sans: "बालाः" },
    { en: "parents", sans: "मातापितरौ" },
    { en: "clockwise", sans: "प्रदक्षिनम्" },
    { en: "counterclockwise", sans: "अप्रदक्षिणम्" },
    { en: "cloudy", sans: "मेघयुक्तः" },
    { en: "clear", sans: "निर्मलः" },
    { en: "comfort", sans: "सुखकर" },
    { en: "discomfort", sans: "दुष्कर" },
    { en: "compliment", sans: "प्रशंसा" },
    { en: "insult", sans: "निन्दा" },
    { en: "compulsory", sans: "आवश्यक" },
    { en: "voluntary", sans: "ऐच्छिक" },
    { en: "hides", sans: "गोपयति" },
    { en: "shows", sans: "प्रकटयति" },
    { en: "consonant", sans: "व्यञ्जनम्" },
    { en: "vowel", sans: "स्वरः" },
    { en: "constant", sans: "अव्ययम्" },
    { en: "variable", sans: "व्ययम्" },
    { en: "construction", sans: "निर्माणम्" },
    { en: "destruction", sans: "संहारम्" },
    { en: "continues", sans: "अनुवर्तते" },
    { en: "stops", sans: "विरमति" },
    { en: "convenient", sans: "अनुकूल" },
    { en: "inconvenient", sans: "प्रतिकूल" },
    { en: "cooked", sans: "पक्व" },
    { en: "uncooked", sans: "अपक्व" },
    { en: "cool", sans: "शीतलम्" },
    { en: "warm", sans: "उष्णम्" },
    { en: "courage", sans: "धैर्यम्" },
    { en: "fear", sans: "भयम्" },
    { en: "brave", sans: "धीरः" },
    { en: "coward", sans: "भीरुः" },
    { en: "confident", sans: "धृष्टः" },
    { en: "timid", sans: "कातरः" },
    { en: "creates", sans: "संसृजति" },
    { en: "destroys", sans: "संहरति" },
    { en: "daughter", sans: "पुत्री" },
    { en: "son", sans: "पुत्रः" },
    { en: "day", sans: "दिनम्" },
    { en: "night", sans: "रात्रिः" },
    { en: "daytime", sans: "दिवा" },
    { en: "nighttime", sans: "निशा" },
    { en: "dead", sans: "मृत" },
    { en: "alive", sans: "जीवित" },
    { en: "death", sans: "मरणम्" },
    { en: "birth", sans: "जन्म" },
    { en: "definite", sans: "निश्चित" },
    { en: "indefinite", sans: "अनिश्चित" },
    { en: "demand", sans: "आवश्यकता" },
    { en: "supply", sans: "उपलभ्यता" },
    { en: "despair", sans: "निराशा" },
    { en: "hope", sans: "आशा" },
    { en: "dim", sans: "निष्प्रभा" },
    { en: "bright", sans: "उज्ज्वल" },
    { en: "dirty", sans: "मलिन" },
    { en: "clean", sans: "स्वच्छ" },
    { en: "Doctor", sans: "वैद्यः" },
    { en: "patient", sans: "रोगी" },
    { en: "downwards", sans: "अधस्तात्" },
    { en: "upwards", sans: "ऊर्ध्वम्" },
    { en: "dry", sans: "शुष्क" },
    { en: "wet", sans: "आर्द्र" },
    { en: "early", sans: "पूर्वम्" },
    { en: "late", sans: "विलम्बेन" },
    { en: "east", sans: "पूर्व" },
    { en: "west", sans: "पश्चिम" },
    { en: "easy", sans: "सरल" },
    { en: "Difficult", sans: "कठिन" },
    { en: "encourage", sans: "प्रोत्साहनम्" },
    { en: "discourage", sans: "भग्नोत्साह" },
    { en: "enjoys", sans: "रोचते" },
    { en: "hates", sans: "न रोचते" },
    { en: "enters", sans: "प्रविशति" },
    { en: "exits", sans: "निर्गच्छति" },
    { en: "entrance", sans: "प्रवेश" },
    { en: "exit", sans: "निर्गम" },
    { en: "expands", sans: "विस्तृणोति" },
    { en: "contracts", sans: "सङ्कुचितं भवति" },
    { en: "external", sans: "बाह्य" },
    { en: "internal", sans: "अभ्यन्तर" },
    { en: "fail", sans: "अनुत्तीर्ण" },
    { en: "pass", sans: "उत्तीर्ण" },
    { en: "far", sans: "दूर" },
    { en: "near", sans: "समीप" },
    { en: "favourable", sans: "अनुकूल" },
    { en: "unfavourable", sans: "प्रतिकूल" },
    { en: "find", sans: "प्राप्त" },
    { en: "lose", sans: "नष्ट" },
    { en: "first", sans: "प्रथम" },
    { en: "last", sans: "अन्तिम" },
    { en: "fixes", sans: "दृढी करोति" },
    { en: "breaks", sans: "भग्नं करोति" },
    { en: "flat", sans: "समतल" },
    { en: "hilly", sans: "पार्वत" },
    { en: "floor", sans: "कुट्टिमम्" },
    { en: "ceiling", sans: "छादः" },
    { en: "folds", sans: "पुटी करोति" },
    { en: "unfolds", sans: "विस्तारयति" },
    { en: "follows", sans: "अनुसरति" },
    { en: "leads", sans: "नेतृत्वं करोति" },
    { en: "for", sans: "कृते" },
    { en: "against", sans: "विरुद्धम्" },
    { en: "foreground", sans: "अग्रभूमिका" },
    { en: "background", sans: "पृष्टभूमिका" },
    { en: "foreign", sans: "विदेशीय" },
    { en: "domestic", sans: "स्वदेशीय" },
    { en: "fortunate", sans: "सुभाग्य" },
    { en: "unfortunate", sans: "दूर्भाग्य" },
    { en: "free", sans: "मुक्तः" },
    { en: "bound", sans: "बद्धः" },
    { en: "frequently", sans: "बहुवारम्" },
    { en: "occasionally", sans: "कदाचित्" },
    { en: "fresh", sans: "अभिनव" },
    { en: "stale", sans: "पर्युषित" },
    { en: "friend", sans: "मित्रम्" },
    { en: "enemy", sans: "शत्रुः" },
    { en: "from here", sans: "इतः" },
    { en: "from there", sans: "ततः" },
    { en: "front", sans: "पुरतः" },
    { en: "rear", sans: "पृष्ठतः" },
    { en: "Full", sans: "पूर्ण" },
    { en: "Empty", sans: "रिक्त" },
    { en: "generous", sans: "उदार" },
    { en: "stingy", sans: "कृपण" },
    { en: "gentle", sans: "कोमल" },
    { en: "rough", sans: "परुष" },
    { en: "giant", sans: "महाकायः" },
    { en: "dwarf", sans: "वामनः" },
    { en: "gives", sans: "ददाति" },
    { en: "takes", sans: "स्वीकरोति" },
    { en: "goes", sans: "गच्छति" },
    { en: "comes", sans: "आगच्छति" },
    { en: "good luck", sans: "सौभाग्यम्" },
    { en: "bad luck", sans: "दौर्भाग्यम्" },
    { en: "good", sans: "शुभम्" },
    { en: "bad",  sans: "अशुभम्" },
    { en: "guest", sans: "अतिथिः" },
    { en: "host", sans: "आतिथेयः" },
    { en: "guilty", sans: "अपराधी" },
    { en: "innocent", sans: "निरपराधी" },
    { en: "happiness", sans: "सन्तोषः" },
    { en: "sadness", sans: "खेदः" },
    { en: "happy", sans: "सुख" },
    { en: "sad", sans: "दुःख" },
    { en: "easy", sans: "सरल" },
    { en: "hard (difficult)", sans: "कठिन" },
    { en: "soft", sans: "मृदु" },
    { en: "hard (firm)", sans: "कठोर" },
    { en: "harmful", sans: "हानिकारक" },
    { en: "harmless", sans: "अहिंसक" },
    { en: "health", sans: "स्वास्थ्यम्" },
    { en: "disease", sans: "रोगम्" },
    { en: "healthy", sans: "आरोग्यम्" },
    { en: "unhealthy", sans: "अनारोग्यम्" },
    { en: "heaven", sans: "स्वर्गम्" },
    { en: "hell", sans: "नरकम्" },
    { en: "here", sans: "अत्र" },
    { en: "there", sans: "तत्र" },
    { en: "hero", sans: "शूरः" },
    { en: "coward", sans: "भीरुः" },
    { en: "helps",   sans: "उपकरोति" },
    { en: "hinders", sans: "अपकरोति" },
    { en: "honest", sans: "निष्कपट" },
    { en: "dishonest", sans: "कपट" },
    { en: "honor", sans: "सम्मानः" },
    { en: "dishonor", sans: "अवमानः" },
    { en: "hopeful", sans: "आशायुक्त" },
    { en: "desperate", sans: "आशाहीन" },
    { en: "horizontal", sans: "तिर्यक्" },
    { en: "vertical",   sans: "ऊर्ध्व" },
    { en: "Hot",  sans: "उष्ण" },
    { en: "Cold", sans: "शीत" },
    { en: "humble", sans: "नम्र" },
    { en: "arrogant", sans: "सदर्प" },
    { en: "hungry", sans: "बुभुक्षित" },
    { en: "satiated", sans: "तृप्त" },
    { en: "Husband", sans: "पतिः" },
    { en: "Wife", sans: "पत्नी" },
    { en: "import", sans: "आयातः" },
    { en: "export", sans: "निर्यातः" },
    { en: "important", sans: "मुख्य" },
    { en: "trivial", sans: "तुच्छ" },
    { en: "in", sans: "अन्तः" },
    { en: "out", sans: "बहिः" },
    { en: "include", sans: "अन्तर्भूत" },
    { en: "exclude", sans: "वर्जित" },
    { en: "increase", sans: "वृद्धिः" },
    { en: "decrease", sans: "ह्रासः" },
    { en: "inhalation", sans: "पूरकः" },
    { en: "exhalation", sans: "रेचकः" },
    { en: "inner", sans: "आभ्यन्तर" },
    { en: "outer", sans: "बहिःस्थ" },
    { en: "interesting", sans: "रोचकम्" },
    { en: "boring",      sans: "नीरसम्" },
    { en: "interior", sans: "आन्तर" },
    { en: "exterior", sans: "बाह्य" },
    { en: "junior", sans: "कनीयान्" },
    { en: "senior", sans: "ज्येष्ठ" },
    { en: "justice", sans: "न्याय" },
    { en: "injustice", sans: "अन्याय" },
    { en: "kind", sans: "दयालु" },
    { en: "cruel", sans: "क्रूर" },
    { en: "knowledge", sans: "विद्या" },
    { en: "ignorance", sans: "अविद्या" },
    { en: "known", sans: "ज्ञात" },
    { en: "unknown", sans: "अज्ञात" },
    { en: "landlord", sans: "भूस्वामी" },
    { en: "tenant", sans: "भाटकी" },
    { en: "laughs", sans: "हसति" },
    { en: "cries", sans: "रोदिति" },
    { en: "lawful", sans: "धर्म्य" },
    { en: "illegal", sans: "अधर्म्य" },
    { en: "lazy", sans: "अलस" },
    { en: "active", sans: "अनलस" },
    { en: "leader", sans: "नायकः" },
    { en: "follower", sans: "अनुचरः" },
    { en: "learns",  sans: "अध्ययनं करोति" },
    { en: "teaches", sans: "पाठयति" },
    { en: "lies down", sans: "शयनं करोति" },
    { en: "stands up", sans: "उत्तिष्ठति" },
    { en: "light (weight)", sans: "लघु" },
    { en: "heavy (weight)", sans: "गुरु" },
    { en: "light (color)", sans: "स्वल्पवर्ण" },
    { en: "dark (color)",  sans: "गाढवर्ण" },
    { en: "bright (brightness)", sans: "दीप्त" },
    { en: "dark",  sans: "तमस्" },
    { en: "likes", sans: "इच्छति" },
    { en: "dislikes", sans: "न इच्छति" },
    { en: "likely", sans: "प्रायेण" },
    { en: "unlikely", sans: "असम्भव" },
    { en: "limited", sans: "मित" },
    { en: "unlimited", sans: "अमित" },
    { en: "liquid", sans: "द्रवः" },
    { en: "solid", sans: "घन" },
    { en: "loser", sans: "पराजितः" },
    { en: "winner", sans: "विजेता" },
    { en: "love", sans: "प्रिय" },
    { en: "hate", sans: "द्वेष" },
    { en: "lovely", sans: "सुन्दर" },
    { en: "terrible", sans: "भयङ्कर" },
    { en: "low", sans: "नीचैः" },
    { en: "high", sans: "उच्चैः" },
    { en: "loyal", sans: "निष्ठावान्" },
    { en: "disloyal", sans: "निष्ठाहीन" },
    { en: "major", sans: "प्रधान" },
    { en: "minor", sans: "अप्रधान" },
    { en: "male", sans: "नरः" },
    { en: "female", sans: "नारी" },
    { en: "man", sans: "पुरुषः" },
    { en: "woman", sans: "स्त्री" },
    { en: "many", sans: "बहवः" },
    { en: "few",  sans: "अल्प" },
    { en: "married",  sans: "विवाहित" },
    { en: "divorced", sans: "विवाहितविच्छिन्न" },
    { en: "melts", sans: "द्रवति" },
    { en: "freezes", sans: "हिमी भवति" },
    { en: "minimum", sans: "न्यूनतम" },
    { en: "maximum", sans: "अधिकतम" },
    { en: "miss", sans: "भ्रष्ट" },
    { en: "hit", sans: "प्रहारः" },
    { en: "moderate", sans: "सन्तुलित" },
    { en: "extreme", sans: "अति" },
    { en: "more", sans: "अधिकम्" },
    { en: "less", sans: "न्यूनम्" },
    { en: "morning", sans: "प्रातः" },
    { en: "evening", sans: "सायम्" },
    { en: "mountain", sans: "पर्वतः" },
    { en: "valley", sans: "शैलसन्धि" },
    { en: "multiplies", sans: "गुणयति" },
    { en: "divides", sans: "विभजति" },
    { en: "natural", sans: "प्राकृतिक" },
    { en: "artificial", sans: "कृत्रिम" },
    { en: "neat", sans: "सुव्यवस्थित" },
    { en: "messy", sans: "अव्यवस्थित" },
    { en: "nice", sans: "सुष्ठु" },
    { en: "awful", sans: "घोर" },
    { en: "niece (brother's daughter)", sans: "भ्रातृजा" },
    { en: "niece (sister's daughter)",  sans: "भागिनेयी" },
    { en: "nephew (brother's son)",     sans: "भ्रातृजः" },
    { en: "nephew (sister's son)",      sans: "भागिनेयः" },
    { en: "noble", sans: "साधु" },
    { en: "wicked", sans: "दुष्ट" },
    { en: "nobody", sans: "न कोऽपि" },
    { en: "everybody", sans: "सर्वे" },
    { en: "noon", sans: "मध्याह्नः" },
    { en: "midnight", sans: "मध्यरात्रि" },
    { en: "north", sans: "उत्तर" },
    { en: "south", sans: "दक्षिण" },
    { en: "not yet", sans: "एतावत्पर्यन्तं" },
    { en: "already", sans: "पूर्वम् एव" },
    { en: "nothing",    sans: "न किमपि" },
    { en: "everything", sans: "सर्वम्" },
    { en: "notices", sans: "लक्षयति" },
    { en: "ignores", sans: "न लक्षयति" },
    { en: "now", sans: "इदानीम्" },
    { en: "later", sans: "अनन्तरं" },
    { en: "obedient", sans: "आज्ञाकारः" },
    { en: "disobedient", sans: "आज्ञाभङ्गकरः" },
    { en: "odd", sans: "विषमसङ्ख्या" },
    { en: "even", sans: "समसंख्या" },
    { en: "often", sans: "बहुवारम्" },
    { en: "seldom", sans: "कदाचित्" },
    { en: "old", sans: "पुरातन" },
    { en: "new", sans: "नूतन" },
    { en: "old (age)", sans: "वृद्धः" },
    { en: "young (age)", sans: "युवकः" },
    { en: "old", sans: "पुरातन" },
    { en: "modern", sans: "आधुनिक" },
    { en: "one", sans: "एक" },
    { en: "many", sans: "अनेक" },
    { en: "opens", sans: "उद्घाटयति" },
    { en: "closes", sans: "पिधानं करोति" },
    { en: "opposes", sans: "विरोधं करोति" },
    { en: "supports", sans: "आधरम् करोति" },
    { en: "optimist", sans: "आशावादी" },
    { en: "pessimist", sans: "निराशावादी" },
    { en: "ordinary", sans: "साधारण" },
    { en: "special", sans: "विशेष" },
    { en: "outskirts (of city)", sans: "नगरप्रान्त" },
    { en: "centre (of city)", sans: "नगरमध्य" },
    { en: "over", sans: "उपरि" },
    { en: "under", sans: "अधः" },
    { en: "partial", sans: "भागः" },
    { en: "total", sans: "पूर्णः" },
    { en: "particular", sans: "विशेषतः" },
    { en: "general", sans: "सामान्यतः" },
    { en: "past", sans: "भूतकालः" },
    { en: "future", sans: "भविष्यत्कालः" },
    { en: "patient", sans: "सहनशीलता" },
    { en: "impatient", sans: "असहनता" },
    { en: "peaceful", sans: "शान्त" },
    { en: "violent", sans: "उग्र" },
    { en: "permanent",  sans: "स्थायी" },
    { en: "temporary",  sans: "आस्थायी" },
    { en: "plants",   sans: "निरोपयति" },
    { en: "harvests", sans: "लुनाति" },
    { en: "Poor", sans: "दरिद्र" },
    { en: "Rich", sans: "धनिक" },
    { en: "possible", sans: "साध्य" },
    { en: "impossible", sans: "असाध्य" },
    { en: "present", sans: "उपस्थित" },
    { en: "absent", sans: "अनुपस्थित" },
    { en: "present (time)", sans: "वर्तमानकालः" },
    { en: "past (time)",    sans: "भूतकालः" },
    { en: "probably", sans: "प्रायेण" },
    { en: "certainly", sans: "निश्चयेन" },
    { en: "prudent", sans: "विमृश्यकारी" },
    { en: "imprudent", sans: "अविमृश्यकारी" },
    { en: "public", sans: "सार्वजनिक" },
    { en: "private", sans: "वैयक्तिक" },
    { en: "pure", sans: "शुद्ध" },
    { en: "impure", sans: "अशुद्ध" },
    { en: "pushes", sans: "नुदति" },
    { en: "pulls",  sans: "आकर्षति" },
    { en: "qualified", sans: "समर्थ" },
    { en: "unqualified", sans: "असमर्थ" },
    { en: "question", sans: "प्रश्नः" },
    { en: "answer", sans: "उत्तरम्" },
    { en: "quiet", sans: "निशब्द" },
    { en: "noisy", sans: "कोलाहलः" },
    { en: "raises", sans: "उत्थापयति" },
    { en: "lowers", sans: "अवतरति" },
    { en: "Rarely", sans: "दुर्लभ" },
    { en: "common", sans: "सामान्य" },
    { en: "real", sans: "सत्यम्" },
    { en: "unreal", sans: "मिथ्या" },
    { en: "receives", sans: "स्वीकरोति" },
    { en: "gives", sans: "ददाति" },
    { en: "regular", sans: "नियत" },
    { en: "irregular", sans: "अनियत" },
    { en: "remembers", sans: "स्मरति" },
    { en: "forgets", sans: "विस्मरति" },
    { en: "repair", sans: "समीकरणम्" },
    { en: "damage", sans: "हानिः" },
    { en: "rests", sans: "विश्रामं करोति" },
    { en: "works", sans: "परिश्रमं करोति" },
    { en: "right (direction)", sans: "दक्षिणतः" },
    { en: "left (direction)", sans: "वामतः" },
    { en: "right", sans: "सम्यक्" },
    { en: "wrong", sans: "असम्यक्" },
    { en: "proper", sans: "उचित" },
    { en: "improper", sans: "अनुचित" },
    { en: "rough", sans: "परुष" },
    { en: "smooth", sans: "अपरुष" },
    { en: "rude", sans: "कठोर" },
    { en: "polite", sans: "विनित" },
    { en: "safe", sans: "सुरक्षित" },
    { en: "dangerous", sans: "अपायकर" },
    { en: "salt", sans: "लवणम्" },
    { en: "sugar", sans: "शर्करा" },
    { en: "same", sans: "समान" },
    { en: "opposite", sans: "विपरीत" },
    { en: "same", sans: "समान" },
    { en: "different", sans: "भिन्न" },
    { en: "satisfactory", sans: "सन्तोषदायक" },
    { en: "unsatisfactory", sans: "असन्तोषदायक" },
    { en: "saves (protects)", sans: "रक्षति" },
    { en: "destroys", sans: "नाशयति" },
    { en: "saves (money)", sans: "सञ्चयम् करोति" },
    { en: "spends",        sans: "व्ययति" },
    { en: "secure", sans: "सुरक्षित" },
    { en: "insecure", sans: "असुरक्षित" },
    { en: "separates", sans: "पृथक् करोति" },
    { en: "joins", sans: "संयोजयति" },
    { en: "serious", sans: "गम्भीरः" },
    { en: "funny", sans: "विनोदी" },
    { en: "servant", sans: "सेवकः" },
    { en: "master", sans: "स्वामी" },
    { en: "sets free", sans: "विमोचयति" },
    { en: "arrests", sans: "बन्धनं करोति" },
    { en: "shallow", sans: "गाधः" },
    { en: "deep", sans: "अगाधः" },
    { en: "short (height)", sans: "ह्रस्वकाय" },
    { en: "tall (height)",  sans: "उन्नतकाय" },
    { en: "short (length)", sans: "ह्रस्व" },
    { en: "long (length)",  sans: "दीर्घ" },
    { en: "shouts", sans: "आक्रोशति" },
    { en: "whispers", sans: "कर्णे कथयति" },
    { en: "shows", sans: "दर्शयति" },
    { en: "hides", sans: "गोपयति" },
    { en: "shrinks", sans: "सङ्कुचति" },
    { en: "grows", sans: "वर्धति" },
    { en: "sick", sans: "अस्वस्थ" },
    { en: "healthy", sans: "स्वस्थ" },
    { en: "simple", sans: "सरल" },
    { en: "complex", sans: "विषम" },
    { en: "singular", sans: "एकवचनम्" },
    { en: "plural", sans: "बहुवचनम्" },
    { en: "sinks",  sans: "निमज्जति" },
    { en: "floats", sans: "प्लवते" },
    { en: "slow", sans: "मन्दम्" },
    { en: "fast", sans: "शीघ्रम्" },
    { en: "sober", sans: "स्थिर" },
    { en: "drunk", sans: "मत्त" },
    { en: "somewhere", sans: "कुत्रापि" },
    { en: "nowhere", sans: "न कुत्रापि" },
    { en: "sorrow", sans: "विषादः" },
    { en: "joy", sans: "आनन्दः" },
    { en: "stands", sans: "तिष्ठति" },
    { en: "sits", sans: "उपविशति" },
    { en: "start", sans: "आरम्भः" },
    { en: "finish", sans: "समाप्तिः" },
    { en: "starts", sans: "आरभ्यते" },
    { en: "stops", sans: "विरमति" },
    { en: "straight", sans: "साक्षात्" },
    { en: "bent", sans: "वक्र" },
    { en: "strange", sans: "विचित्र" },
    { en: "normal", sans: "सामान्य" },
    { en: "stranger", sans: "परः" },
    { en: "acquaintance", sans: "परिचितः" },
    { en: "strict", sans: "निष्ठुर" },
    { en: "lenient", sans: "उदार" },
    { en: "strong (person)", sans: "बलवान्" },
    { en: "weak (person)", sans: "दुर्बल" },
    { en: "student", sans: "छात्रः" },
    { en: "teacher", sans: "अध्यापकः" },
    { en: "stupid", sans: "मूर्ख" },
    { en: "intelligent", sans: "बुद्धिमान्" },
    { en: "subtle", sans: "सूक्ष्म" },
    { en: "gross", sans: "स्थूल" },
    { en: "success", sans: "सफलता" },
    { en: "failure", sans: "असफलता" },
    { en: "summer", sans: "ग्रीष्मकाल" },
    { en: "winter", sans: "शीतकाल" },
    { en: "sun", sans: "सूर्यः" },
    { en: "moon", sans: "चन्द्रः" },
    { en: "sunny",   sans: "सूर्यप्रकाशित" },
    { en: "cloudy",  sans: "मेघाच्छन्न" },
    { en: "sunrise", sans: "सूर्योदयः" },
    { en: "sunset",  sans: "सूर्यास्तः" },
    { en: "dawn", sans: "प्रातःकालः" },
    { en: "dusk", sans: "सन्ध्या" },
    { en: "sweet", sans: "मधुरम्" },
    { en: "bitter", sans: "तिक्तम्" },
    { en: "sour",       sans: "अम्लः" },
    { en: "astringent", sans: "कषायः" },
    { en: "salty",      sans: "लवणः" },
    { en: "spicy (hot)",  sans: "कटुकः" },
    { en: "thin", sans: "कृश" },
    { en: "fat", sans: "स्थूल" },
    { en: "thirsty", sans: "पिपासित" },
    { en: "quenched", sans: "परिशमित" },
    { en: "tight", sans: "दृढ" },
    { en: "loose", sans: "शिथिल" },
    { en: "tired", sans: "श्रान्त" },
    { en: "relaxed", sans: "विश्राम" },
    { en: "tiny", sans: "लघु" },
    { en: "huge", sans: "बृहत्" },
    { en: "together", sans: "मिलित्वा" },
    { en: "apart", sans: "पृथक्" },
    { en: "top", sans: "उपरितन" },
    { en: "bottom", sans: "तलम्" },
    { en: "tough", sans: "कठिन" },
    { en: "easy", sans: "सुलभ" },
    { en: "transparent", sans: "पारदर्शक" },
    { en: "opaque", sans: "प्रकाशभेद्य" },
    { en: "true", sans: "सत्य" },
    { en: "false", sans: "असत्य" },
    { en: "trust", sans: "विश्वासः" },
    { en: "mistrust", sans: "अविश्वासः" },
    { en: "truth",      sans: "सत्यम्" },
    { en: "falsehood",  sans: "मिथ्यात्वम्" },
    { en: "understands", sans: "अवगच्छति" },
    { en: "misunderstands", sans: "अन्यता गृह्णाति" },
    { en: "unites", sans: "सङ्घटयति" },
    { en: "divides", sans: "विभजति" },
    { en: "unity", sans: "एकता" },
    { en: "diversity", sans: "अनेकता" },
    { en: "up", sans: "उपरि" },
    { en: "down", sans: "अधः" },
    { en: "upstairs", sans: "उपरितनतल" },
    { en: "downstairs", sans: "अधस्तनतल" },
    { en: "us", sans: "वयम्" },
    { en: "them", sans: "ते" },
    { en: "useful", sans: "उपयुक्त" },
    { en: "useless", sans: "अनुपयुक्त" },
    { en: "vacant", sans: "रिक्त" },
    { en: "occupied", sans: "व्याप्त" },
    { en: "vast", sans: "बृहत्" },
    { en: "tiny", sans: "लघु" },
    { en: "victory", sans: "जयः" },
    { en: "defeat", sans: "पराजयः" },
    { en: "village", sans: "ग्रामः" },
    { en: "town", sans: "नगरम्" },
    { en: "virtue", sans: "धर्मः" },
    { en: "vice", sans: "अधर्मः" },
    { en: "visible", sans: "व्यक्त" },
    { en: "invisible", sans: "अव्यक्त" },
    { en: "war", sans: "युद्धम्" },
    { en: "peace", sans: "सन्धि" },
    { en: "wealth", sans: "सम्पत्तिः" },
    { en: "poverty", sans: "दारिद्र्यम्" },
    { en: "whole", sans: "सम्पूर्ण" },
    { en: "part",  sans: "भागः" },
    { en: "wide", sans: "विस्तृत" },
    { en: "narrow", sans: "सङ्कीर्ण" },
    { en: "wins", sans: "जयति" },
    { en: "loses", sans: "पराजयते" },
    { en: "wisdom", sans: "विवेकम्" },
    { en: "stupidity", sans: "मूढता" },
    { en: "wise", sans: "विवेकी" },
    { en: "foolish", sans: "मूर्खः" },
    { en: "yes", sans: "आम्" },
    { en: "no", sans: "न" }
];
