const quizData = [
    { en: "Proximity", sans: "संहिता" },
    { en: "Sequence, order", sans: "क्रम" },
    { en: "Change, modification", sans: "विकार" },
    { en: "cut", sans: "छेद" },
    { en: "both", sans: "उभय" },
    { en: "wolf", sans: "वृक" },
    { en: "always", sans: "नित्य" },
    { en: "Optional", sans: "विकल्प" },
    { en: "separation, division", sans: "विच्छेद" },
    { en: "temptation, lure", sans: "प्रलोभनम्" },
    { en: "bait", sans: "आमिषम्" },
    { en: "snare/trap", sans: "पाशः" },
    { en: "job", sans: "उद्योग" },
    { en: "left, gave up", sans: "त्यक्तवान्" },
    { en: "house confinement", sans: "गृहबन्धनम्" },
    { en: "unmarried", sans: "अविवाहित" },
    { en: "buttermilk", sans: "तक्रम्" },
    { en: "prepared, completed, ready", sans: "सिद्धः (adj)" },
    { en: "eyesight, vision, attitude", sans: "दृष्टिः (f)" },
    { en: "creation, nature", sans: "सृष्टिः (f)" },
    { en: "since, beginning with", sans: "प्रभृति (ind)" },
    { en: "upto, until", sans: "पर्यन्तम् (ind)" },
    { en: "careful", sans: "सावधान (adj)" },
    { en: "change, alteration, modification", sans: "परिवर्तनम् (n)" },
    { en: "present day, modern", sans: "इदानीन्तन (adj)" },
    { en: "engaged, busy", sans: "व्यस्त (adj)" },
    { en: "big, tall, great", sans: "बृहत् (adj)" },
    { en: "except", sans: "विहाय (ind)" },
    { en: "burning, burning sensation", sans: "निदाह" },
    { en: "wave, tide", sans: "तरङ्गः (m)" },
    { en: "riddle", sans: "प्रहेलिका (f)" },
    { en: "young animal, cub", sans: "शावकः (f)" },
    { en: "incense stick", sans: "सुगन्धवर्तिका (f)" },
    { en: "walk, stroll", sans: "विहारः (m)" },
    { en: "flour batter", sans: "पिष्टम् (n)" },
    { en: "hunter", sans: "व्याधः (m)" },
    { en: "opportunity", sans: "अवसरः (m)" },
    { en: "candle", sans: "सिक्थवर्तिका (f)" },
    { en: "wastefully", sans: "वृथा (ind)" },
    { en: "although, even though", sans: "यद्यपि (ind)" },
    { en: "yet, even then", sans: "तथापि" },
    { en: "I draw, I create, I compose", sans: "रचयामि" },
    { en: "broom", sans: "सम्मार्जनी (f)" },
    { en: "powder", sans: "चूर्णम् (n)" },
    { en: "talcum powder", sans: "सुवासकम् (n)" },
    { en: "decorates", sans: "अलङ्करोति" },
    { en: "beautifies, makes beautiful", sans: "शोभयति" },
    { en: "daily, everyday", sans: "प्रतिदिनम् (ind)" },
    { en: "sometimes", sans: "कदाचित् (ind)" },
    { en: "hold, seize", sans: "धरति (v)" },
    { en: "wears, supports", sans: "धरति (v)" },
    { en: "to make someone wear", sans: "धारयति (v)" },
    { en: "to leave, to abandon", sans: "त्यक्तुम्" },
    { en: "watery", sans: "जलमय (adj)" },
    { en: "decision", sans: "निर्णयः (m)" },
    { en: "he/she decides", sans: "निर्णयति (v)" },
    { en: "exercise", sans: "व्यायामः (m)" },
    { en: "I will get up", sans: "उत्थास्यामि" },
    { en: "advertises, promotes", sans: "प्रचारयति" },
    { en: "arranged, placed in order", sans: "व्यवस्थितः" },
    { en: "almost, estimate", sans: "प्रायः (adv)" },
    { en: "since, beginning with", sans: "प्रभृति (ind)" },
    { en: "travel", sans: "भ्रमणम् (n), यात्रा (√या)(f)" },
    { en: "traveller", sans: "यात्रिकः (m)" },
    { en: "correctly, rightly", sans: "सम्यक्तया (f)" },
    { en: "cow shed", sans: "गोशाला (f)" },
    { en: "vomit", sans: "वमनम् (n)" },
    { en: "music", sans: "सङ्गीतम् (n)" },
    { en: "some", sans: "केचन" },
    { en: "having entered", sans: "प्रविश्य" },
    { en: "enters", sans: "प्रविशति" },
    { en: "weight", sans: "भारः (m)" },
    { en: "light weighted", sans: "लगुभारः (adj)" },
    { en: "gain weight", sans: "भारं वर्धय" },
    { en: "lose weight", sans: "भारं घटय" },
    { en: "informed, pointed out", sans: "सूचित (adj)" },
    { en: "to another (person)", sans: "अन्यस्मै" },
    { en: "building", sans: "भवनम् (n)" },
    { en: "construction", sans: "निर्माणम्" },
    { en: "constructs, builds", sans: "निर्माति" },
    { en: "by you", sans: "त्वया (ind)" },
    { en: "meeting", sans: "मेलनम्" },
    { en: "guilty (of a crime)", sans: "दोषी (m)" },
    { en: "feeling guilty, remorse", sans: "पश्चात्तापः" },
    { en: "innocent (like a child)", sans: "मुग्ध" },
    { en: "innocent (of a crime)", sans: "निर्दोषी" },
    { en: "By you", sans: "भवता" },
    { en: "Increases, expands, grows", sans: "वर्धयति" },
    { en: "Holiday, vacation, opportunity", sans: "अवकाशः (m)" },
    { en: "Further more, besides this, more", sans: "इतोऽपि" },
    { en: "Count", sans: "गणय" },
    { en: "Evidence", sans: "प्रमाणम्" },
    { en: "Rule", sans: "नियमः (m)" },
    { en: "Hides, conceals", sans: "गोपयति (v)" },
    { en: "Finds, gets", sans: "विन्दति (v)" },
    { en: "He/she pressed", sans: "नोदयति (v)" },
    { en: "Destroys", sans: "नाशयति (v)" },
    { en: "Waste (noun)", sans: "अवकरः (m)" },
    { en: "To waste", sans: "व्यर्थं" },
    { en: "Dustbin", sans: "अवकरिका (f)" },
    { en: "Silence", sans: "निःशब्दम् (n)" },
    { en: "Silent", sans: "मौनम् (n)" },
    { en: "Each other, mutually", sans: "परस्परम् (ind)" },
    { en: "For how long, how much time", sans: "कियत्कालम् (ind)" },
    { en: "Hat", sans: "शिरस्त्रम् (n)" },
    { en: "Free", sans: "मुक्त (adj)" },
    { en: "Balance, left over, remainder", sans: "शेषम् (adj), अवशिष्टम् (adj)" },
    { en: "Unconquered, invincible", sans: "अपराजित (adj)" },
    { en: "Conquered, vanquished", sans: "पराजित (adj)" },
    { en: "Longing, separation", sans: "विरह (m)" },
    { en: "A few, some", sans: "कतिपय (adj)" },
    { en: "Vegetable", sans: "शाकाम्‌ (n)" },
    { en: "Solution (to a problem)", sans: "समाधानम् (n)" },
    { en: "Soldier", sans: "योधः (M), सैनिकः (m)" },
    { en: "Brave", sans: "शूरः (M) धीर (adj)" },
    { en: "Opposite", sans: "विपरीत (adj) विलोम (adj)" },
    { en: "Direction", sans: "दिशा (f), दिक् (f)" },
    { en: "Unripe", sans: "अपक्व (adj)" },
    { en: "Very, greatly", sans: "अत्यन्तम् (adj)" },
    { en: "Exceedingly", sans: "अतिशयेन (ind)" },
    { en: "Rainbow", sans: "इन्द्रधनुः (m)" },
    { en: "Same, alike", sans: "सदृश (adj)" },
    { en: "Unfavorable", sans: "प्रतिकूल (adj)" },
    { en: "Favorable", sans: "अनुकूल (adj)" },
    { en: "is envious of", sans: "ईर्ष्यति (v)" },
    { en: "causes pain, bears ill will", sans: "द्रुह्यति (v)" },
    { en: "people, citizens, population", sans: "प्रजा (f)" },
    { en: "eye", sans: "लोचनम् (n)" },
    { en: "gives", sans: "यच्छति (v) √दा" },
    { en: "noble people", sans: "साधवः (m)" },
    { en: "best among the sages", sans: "मुनिवरः (m)" },
    { en: "for the benefit of others", sans: "परोपकारः (m)" },
    { en: "dark, dark colored", sans: "श्यामलक (adj)" },
    { en: "benefit", sans: "श्रेयः (m)" },
    { en: "better, superior", sans: "श्रेष्ठ (adj)" },
    { en: "theoretical knowledge", sans: "ज्ञानम् (n)" },
    { en: "direct realization or experiential knowledge", sans: "विज्ञानम् (n)" },
    { en: "portion, share", sans: "भागः (m)" },
    { en: "division, section", sans: "विभागः (m)" },
    { en: "silently, quietly", sans: "तुष्णीम्" },
    { en: "the state of being silent", sans: "तूष्णीम्भावः (m) मौनम् (n)" },
    { en: "married couple", sans: "दम्पती (m)" },
    { en: "a pair, a couple", sans: "युगलम् (n)" },
    { en: "male-female pair", sans: "मिथुनम् (m,n)" },
    { en: "cause, reason, motive", sans: "हेतुः (m)" },
    { en: "jealousy, envy, spite", sans: "असूया (f)" },
    { en: "causes, creates", sans: "कल्पते (v)" },
    { en: "in place of, instead of", sans: "स्थाने" },
    { en: "in comparison with", sans: "अपेक्षया (ind)" },
    { en: "take, fetch, bring", sans: "आहर (v)" },
    { en: "kidnapped, abducted", sans: "अपहरत् (v)"}
    { en: "mandatory, compulsory", sans: "अनिवार्यम् (adj)" },
    { en: "Tube", sans: "नलिका (f)" },
    { en: "to defeat, be victorious", sans: "विजयते (v)" },
    { en: "I worship", sans: "भजे (v)" },
    { en: "Night", sans: "निशा (f)" },
    { en: "Touches", sans: "स्पृशति (v)" },
    { en: "Successful", sans: "सफल (adj)" },
    { en: "Path, course", sans: "अयनम् (n)" },
    { en: "prosperous", sans: "समृद्ध (adj)" },
    { en: "Tasty", sans: "स्वादु (adj), रुचिकर (adj)" },
    { en: "sings, chirps", sans: "कूजति (v)" },
    { en: "Roars", sans: "गर्जति (v)" },
    { en: "gradually", sans: "क्रमशः (ind)" },
    { en: "little by little, bit by bit", sans: "अल्पम् अल्पम् (ind), शनैः शनैः (ind)" },
    { en: "Lid, covering", sans: "पिधानम् (n)" },
    { en: "wrapper, covering", sans: "आवरणम् (n)" },
    { en: "tour, journey", sans: "प्रवासः (m)" },
    { en: "lost", sans: "नष्ट (adj)" },
    { en: "lost, robbed, disappeared", sans: "लुप्त (adj)" },
    { en: "joins, combines, unites", sans: "संयोजयति (v) (√युज्)" },
    { en: "father", sans: "जनकः (m)" },
    { en: "mother", sans: "जननी (f)" },
    { en: "greed", sans: "लोभः (m)" },
    { en: "digs", sans: "खनति (v)" },
    { en: "great", sans: "महान् (m) महती (f) (√महत्)" },
    { en: "more and more", sans: "अधिकाधिक (adj)" },
    { en: "the act of giving", sans: "प्रदान (adj)" },
    { en: "for each (individual)", sans: "प्रत्येकस्मै" },
    { en: "advertisement", sans: "विज्ञापनम् (n)" },
    { en: "journalist", sans: "वार्तिकः (m)" },
    { en: "beneficiary, experiencer", sans: "भोक्ता (m)" },
    { en: "compassionate", sans: "कृपालु्ः (म) दयालुः (m)" },
    { en: "austerity, penance, ascetic discipline", sans: "तपः (n)" },
    { en: "water", sans: "अम्बु (n)" },
    { en: "eye", sans: "अक्षि (n)" },
];

/*
     todo_priya was here

    { en: "Monkey", sans: "मर्कटः" },
    { en: "feeling", sans: "भव" },
    { en: "indicators", sans: "सूचक" },
    { en: "cart", sans: "शकटः" },
    { en: "journey", sans: "प्रयाण" },
    { en: "instrument", sans: "साधन" },
    { en: "Enters", sans: "pravishati" },
    { en: "market, shop", sans: "आपणः (M)" },
    { en: "enough, capable of, fit for, don't, ", sans: "अलम्" },
    { en: "enjoyment", sans: "भोग" },
    { en: "pond, water reservoir", sans: "तडग" },
    { en: "is jealous of", sans: "असुयति" },
    { en: "leaders, politicians", sans: "नेतारः" },
    { en: "people", sans: "जनान्" },
    { en: "averts, escapes", sans: "जुगुप्सते" },
    { en: "retires", sans: "विरमति" },
    { en: "slips", sans: "प्रमाद्यति" },
    { en: "fears", sans: "बिभेति" },
    { en: "protects", sans: "रक्षति" },
    { en: "water", sans: "तोयम् (N)" },
    { en: "archer", sans: "धनुर्धरः (M)" },
    { en: "strong, powerful, mighty", sans: "बलवान्" },
    { en: "Desire, wish, longing", sans: "कामः (M)" },
    { en: "above", sans: "उपरि" },
    { en: "below", sans: "अधः" },
    { en: "in front", sans: "पुरतः/अग्रे/समक्षम्" },
    { en: "behind", sans: "पश्चात्/पृष्ठतः" },
    { en: "on the right", sans: "दक्षिणतः" },
    { en: "on the left", sans: "वामतः" },
    { en: "for the sake of", sans: "कृते" },
    { en: "on both sides, in both ways", sans: "उभयतः" },
    { en: "around, on all sides", sans: "परितः" },
    { en: "and, and so, in that way, similarly", sans: "तथा" },
    { en: "banyan tree", sans: "वटवृक्षः (M)" },
    { en: "equal to", sans: "तुल्य (Adj)" },
    { en: "equal, same", sans: "समान (Adj)" },
    { en: "counts", sans: "गणयति" },
    { en: "finally, at last", sans: "अन्ततः" },
    { en: "contact, union, meeting", sans: "संयोग" },
    { en: "pervading, encompassing, extending", sans: "अभिव्यापक" },
    { en: "in the evening", sans: "सायङ्काले" },
    { en: "reality", sans: "वस्तुनि" },
    { en: "objects, things", sans: "वस्तूनि" },
    { en: "humility", sans: "विनयः (M)" },
    { en: "falls", sans: "पतति" },
    { en: "places, sets down", sans: "स्थापयति" },
    { en: "throws", sans: "क्षिपति" },
    { en: "sends", sans: "प्रेषयति" },
    { en: "enters", sans: "प्रविशति" },
    { en: "leaves, goes out, exits", sans: "निर्गच्छति, प्रयाति" },
    { en: "pebble, stone", sans: "पाषाण (M)" },
    { en: "loves", sans: "स्निह्यति" },
    { en: "expert, skilled", sans: "कुशलः, निपुणः" },
    { en: "archery", sans: "धनुर्विद्या (F)" },
    { en: "anklet", sans: "नूपुरा (F)" },
    { en: "seed", sans: "बीज" },
    { en: "sow", sans: "वपति (V)" },
    { en: "table, desk", sans: "उत्पीठिका (F)" },
    { en: "police, guard", sans: "आरक्षकः (M)" },
    { en: "holds, grasps", sans: "गृह्णाति (V)" },
    { en: "milkman", sans: "गोपः (M)" },
    { en: "course, path, direction", sans: "अयन" },
    { en: "earth", sans: "मही" },
    { en: "lord, master, husband", sans: "पतिः" },
    { en: "", sans: "" },



    ===========================

    { en: "Team", sans: "" },
    { en: "Prefer", sans: "" },
    { en: "Preference", sans: "" },
    { en: "Repeat", sans: "" },
    { en: "Relax", sans: "" },
    { en: "Revision", sans: "" },
    { en: "Instruction", sans: "" },
    { en: "apply", sans: "" },
    { en: "pocket", sans: "" },
    { en: "library", sans: "" },
    { en: "bank", sans: "" },
    { en: "shop", sans: "" },
    { en: "market", sans: "" },
    { en: "", sans: "प्रत्येकशस् (Ind)" },
    { en: "transformation", sans: "" },
    { en: "reflection", sans: "" },
    { en: "prayer", sans: "" },
    { en: "confusion", sans: "" },
    { en: "disturb", sans: "" },
    { en: "dark", sans: "" },
    { en: "bright", sans: "" },
    { en: "Exits/leaves", sans: "" },
    { en: "applies", sans: "" },
    { en: "other things, etc", sans: "आदि" },
    { en: "potter", sans: "कुम्भकारः" },
    { en: "", sans: "" },
    { en: "", sans: "" },
    { en: "", sans: "" },
    { en: "", sans: "" },
    { en: "", sans: "" },
    { en: "", sans: "" },
    { en: "", sans: "" },

प्रबन्धकः — manager (general, business/office) ✅
व्यवस्थापकः — manager, organizer, administrator
सञ्चालकः — manager, director, operator
अधिकारी — officer, person in charge
nirdeshika
तन्त्रज्ञः

श्रावयतु
निमीलयतु
उन्मीलयतु

krisham
bheda
svasaa
dataraha

    kanta pata
    duralabaha
    chalani - sieve
    shastram - weapon?
    upanayasaha -
    janabhasha -
    jail, prison - kaidashala?
    janabhasha
    shastram = weapon

    klesha
    kshina
    parampara

    shapes category in vocab
    color category in vocab


     pravasam
     strong - weak
     North, South, East, West
     shirt = yutakam
     pant = urukam
     kwatitam
     serve = pariveshanam
     improvement = sudharanam
     itopi, tatopi

     add अपराजितः, पराजितः to antonyms
     add hat to clothing category

     Professions category
    { en: "potter", sans: "कुम्भकारः" },


*/
