const quizData = [
    { en: "proximity", sans: "संहिता" },
    { en: "sequence, order", sans: "क्रम" },
    { en: "change, modification", sans: "विकार" },
    { en: "cut", sans: "छेद" },
    { en: "both", sans: "उभय" },
    { en: "wolf", sans: "वृक" },
    { en: "always", sans: "नित्य" },
    { en: "Optional", sans: "विकल्प" },
    { en: "separation, division", sans: "विच्छेद" },
    { en: "temptation, lure", sans: "प्रलोभनम्" },
    { en: "bait", sans: "आमिषम्" },
    { en: "snare/trap", sans: "पाशः" },
    { en: "job", sans: "उद्योग" },
    { en: "left, gave up", sans: "त्यक्तवान्" },
    { en: "house confinement", sans: "गृहबन्धनम्" },
    { en: "unmarried", sans: "अविवाहित" },
    { en: "buttermilk", sans: "तक्रम्" },
    { en: "prepared, completed, ready", sans: "सिद्धः (Adj)" },
    { en: "eyesight, vision, attitude", sans: "दृष्टिः (F)" },
    { en: "creation, nature", sans: "सृष्टिः (F)" },
    { en: "since, beginning with", sans: "प्रभृति (Indecl)" },
    { en: "upto, until", sans: "पर्यन्तम् (Indecl)" },
    { en: "careful", sans: "सावधान (Adj)" },
    { en: "change, alteration, modification", sans: "परिवर्तनम् (N)" },
    { en: "present day, modern", sans: "इदानीन्तन (Adj)" },
    { en: "engaged, busy", sans: "व्यस्त (Adj)" },
    { en: "big, tall, great", sans: "बृहत् (Adj)" },
    { en: "except", sans: "विहाय (Indecl)" },
    { en: "burning, burning sensation", sans: "निदाह" },
    { en: "wave, tide", sans: "तरङ्गः (M)" },
    { en: "riddle", sans: "प्रहेलिका (F)" },
    { en: "young animal, cub", sans: "शावकः (M)" },
    { en: "incense stick", sans: "सुगन्धवर्तिका (F)" },
    { en: "walk, stroll", sans: "विहारः (M)" },
    { en: "flour batter", sans: "पिष्टम् (N)" },
    { en: "hunter", sans: "व्याधः (M)" },
    { en: "opportunity", sans: "अवसरः (M)" },
    { en: "candle", sans: "सिक्थवर्तिका (F)" },
    { en: "wastefully", sans: "वृथा (Indecl)" },
    { en: "although, even though", sans: "यद्यपि (Indecl)" },
    { en: "yet, even then", sans: "तथापि" },
    { en: "I draw, I create, I compose", sans: "रचयामि" },
    { en: "broom", sans: "सम्मार्जनी (F)" },
    { en: "powder", sans: "चूर्णम् (N)" },
    { en: "talcum powder", sans: "सुवासकम् (N)" },
    { en: "decorates", sans: "अलङ्करोति" },
    { en: "beautifies, makes beautiful", sans: "शोभयति" },
    { en: "daily, everyday", sans: "प्रतिदिनम् (Indecl)" },
    { en: "sometimes", sans: "कदाचित् (Indecl)" },
    { en: "hold, seize", sans: "धरति (Verb)" },
    { en: "wears, supports", sans: "धरति (Verb)" },
    { en: "to make someone wear", sans: "धारयति (Verb)" },
    { en: "to leave, to abandon", sans: "त्यक्तुम्" },
    { en: "watery", sans: "जलमय (Adj)" },
    { en: "decision", sans: "निर्णयः (M)" },
    { en: "he/she decides", sans: "निर्णयति (Verb)" },
    { en: "exercise", sans: "व्यायामः (M)" },
    { en: "I will get up", sans: "उत्थास्यामि" },
    { en: "advertises, promotes", sans: "प्रचारयति" },
    { en: "arranged, placed in order", sans: "व्यवस्थितः" },
    { en: "almost, estimate", sans: "प्रायः (Adv)" },
    { en: "since, beginning with", sans: "प्रभृति (Indecl)" },
    { en: "travel", sans: "भ्रमणम् (N), यात्रा (F)" },
    { en: "traveller", sans: "यात्रिकः (M)" },
    { en: "correctly, rightly", sans: "सम्यक्तया (F)" },
    { en: "cow shed", sans: "गोशाला (F)" },
    { en: "vomit", sans: "वमनम् (N)" },
    { en: "music", sans: "सङ्गीतम् (N)" },
    { en: "some", sans: "केचन" },
    { en: "having entered", sans: "प्रविश्य" },
    { en: "enters", sans: "प्रविशति" },
    { en: "weight", sans: "भारः (M)" },
    { en: "light weighted", sans: "लगुभारः (Adj)" },
    { en: "gain weight", sans: "भारं वर्धय" },
    { en: "lose weight", sans: "भारं घटय" },
    { en: "informed, pointed out", sans: "सूचित (Adj)" },
    { en: "to another (person)", sans: "अन्यस्मै" },
    { en: "building", sans: "भवनम् (N)" },
    { en: "construction", sans: "निर्माणम्" },
    { en: "constructs, builds", sans: "निर्माति" },
    { en: "by you", sans: "त्वया (Indecl)" },
    { en: "meeting", sans: "मेलनम्" },
    { en: "guilty (of a crime)", sans: "दोषी (M)" },
    { en: "feeling guilty, remorse", sans: "पश्चात्तापः" },
    { en: "innocent (like a child)", sans: "मुग्ध" },
    { en: "innocent (of a crime)", sans: "निर्दोषी" },
    { en: "By you", sans: "भवता" },
    { en: "Increases, expands, grows", sans: "वर्धयति" },
    { en: "Holiday, vacation, opportunity", sans: "अवकाशः (M)" },
    { en: "Further more, besides this, more", sans: "इतोऽपि" },
    { en: "Count", sans: "गणय" },
    { en: "Evidence", sans: "प्रमाणम्" },
    { en: "Rule", sans: "नियमः (M)" },
    { en: "Hides, conceals", sans: "गोपयति (Verb)" },
    { en: "Finds, gets", sans: "विन्दति (Verb)" },
    { en: "He/she pressed", sans: "नोदयति (Verb)" },
    { en: "Destroys", sans: "नाशयति (Verb)" },
    { en: "Waste (noun)", sans: "अवकरः (M)" },
    { en: "To waste", sans: "व्यर्थं" },
    { en: "Dustbin", sans: "अवकरिका (F)" },
    { en: "Silence", sans: "निःशब्दम् (N)" },
    { en: "Silent", sans: "मौनम् (N)" },
];

/*
    { en: "each other, mutually", sans: "परस्परम् (Indecl TODO)" },

    { en: "For how long, how much time", sans: कियत्कालं" },
    { en: "Hat", sans: "शीर्षकम् (N)" },
    { en: "Free", sans: "मुक्त" },
    { en: "Balance, left over, remainder", sans: "शेषम् (N), अवशिष्टम्" },
    { en: "", sans: "" },
    { en: "", sans: "" },
     pravasam
     strong - weak
     North, South, East, West
     shirt = yutakam
     pant = urukam
     kwatitam
     serve = pariveshanam
     improvement = sudharanam
     itopi, tatopi


*/
