const quizData = [
{ en: "a certain", sans: "कश्चन" },
{ en: "accomplished", sans: "साधितवान्" },
{ en: "achieved", sans: "साधितवान्" },
{ en: "an arrow", sans: "बाणः" },
{ en: "any", sans: "किमपि" },
{ en: "anything", sans: "किमपि" },
{ en: "as much as possible", sans: "यावच्छक्यं" },
{ en: "ascetic", sans: "संन्यासी" },
{ en: "asked", sans: "पृष्टवान्" },
{ en: "at the target", sans: "लक्ष्ये" },
{ en: "attained", sans: "सिद्धम्" },
{ en: "compared to me", sans: "ममापेक्षया" },
{ en: "definite", sans: "निर्दिष्टं" },
{ en: "does not exist", sans: "नास्ति" },
{ en: "doing", sans: "कुर्वन्" },
{ en: "even", sans: "अपि" },
{ en: "experiences", sans: "अनुभवति" },
{ en: "famous", sans: "कीर्तिशालिनः" },
{ en: "filled", sans: "व्याप्तम्" },
{ en: "for what purpose", sans: "किमर्थम्" },
{ en: "forest", sans: "अरण्यं" },
{ en: "forty years old", sans: "चत्वारिंशद्वर्षीयः" },
{ en: "from now onwards", sans: "इतः परं" },
{ en: "gentle smile", sans: "मन्दहासं" },
{ en: "goal", sans: "लक्ष्यम्" },
{ en: "have come", sans: "आगतवान्?" },
{ en: "he", sans: "सः" },
{ en: "here", sans: "अत्र" },
{ en: "however", sans: "तु" },
{ en: "I", sans: "अहं" },
{ en: "in his", sans: "तस्य" },
{ en: "in life", sans: "जन्मनि" },
{ en: "in life", sans: "जीविते" },
{ en: "in the situation", sans: "स्थिते" },
{ en: "isn't it", sans: "किल" },
{ en: "itself", sans: "एव" },
{ en: "life", sans: "जीवनं" },
{ en: "like", sans: "इव" },
{ en: "live", sans: "जीवामि" },
{ en: "millionaires", sans: "लक्षाधीशाः" },
{ en: "mind", sans: "मनसि" },
{ en: "my", sans: "मम" },
{ en: "nameless", sans: "अनामधेयः" },
{ en: "not", sans: "न" },
{ en: "of equal age", sans: "समवयस्काः" },
{ en: "on that day", sans: "तद्दिने" },
{ en: "on the path", sans: "मार्गे" },
{ en: "once", sans: "कदाचित्" },
{ en: "others", sans: "इतरे" },
{ en: "regret", sans: "खेदः" },
{ en: "said", sans: "उक्तवान्" },
{ en: "showing", sans: "प्रकटयन्" },
{ en: "so much", sans: "तावत्" },
{ en: "some", sans: "केचन" },
{ en: "sorrow", sans: "खेदं" },
{ en: "sorrow", sans: "दुःखम्" },
{ en: "target", sans: "लक्ष्यम्" },
{ en: "the ascetic", sans: "संन्यासी" },
{ en: "then", sans: "तदा" },
{ en: "then", sans: "तर्हि" },
{ en: "there", sans: "तत्र" },
{ en: "therefore", sans: "अतः" },
{ en: "thinking", sans: "चिन्तयन्" },
{ en: "this", sans: "एतत्" },
{ en: "thought", sans: "आलोचना" },
{ en: "through this", sans: "एतेन" },
{ en: "thus", sans: "इति" },
{ en: "thus", sans: "एवं" },
{ en: "to be accomplished", sans: "साधनीयम्" },
{ en: "to the forest", sans: "अरण्यं" },
{ en: "useless", sans: "व्यर्थम्" },
{ en: "was", sans: "आसीत्" },
{ en: "what", sans: "किं" },
{ en: "why", sans: "किमर्थम्?" },
{ en: "wisdom", sans: "विवेकं" },
{ en: "with contentment", sans: "तृप्त्या" },
{ en: "with detachment", sans: "वैराग्येण" },
{ en: "with fierce animals", sans: "क्रूरमृगैः" },
{ en: "work", sans: "कार्यं" },
{ en: "you", sans: "भवान्" },
{ en: "younger", sans: "कनिष्ठाः" },
{ en: "your's", sans: "भवतः?" },
];
