const quizData = [
{ en: "a certain", sans: "कस्यचित्" },
{ en: "a little", sans: "किञ्चित्" },
{ en: "and", sans: "च" },
{ en: "as if", sans: "इव" },
{ en: "bought", sans: "क्रीतवान्" },
{ en: "by eloquence", sans: "वाक्चातुर्येण" },
{ en: "by good fortune", sans: "सौभाग्येन" },
{ en: "certainly", sans: "निश्चयेन" },
{ en: "city", sans: "नगरं" },
{ en: "Devarāja's", sans: "देवराजस्य" },
{ en: "distance", sans: "दूरं" },
{ en: "draped", sans: "धारितवान्" },
{ en: "even", sans: "अपि" },
{ en: "excellent", sans: "उत्तमं" },
{ en: "for now", sans: "तावत्" },
{ en: "for the purpose of business/work", sans: "कार्यनिमित्तं" },
{ en: "had gone", sans: "गतवान्" },
{ en: "having called", sans: "आहूय" },
{ en: "having completed", sans: "समाप्य" },
{ en: "having given", sans: "दत्त्वा" },
{ en: "having gone", sans: "गत्वा" },
{ en: "having worn", sans: "धृत्वा" },
{ en: "he", sans: "सः" },
{ en: "here", sans: "अत्र" },
{ en: "high", sans: "अधिकम्" },
{ en: "identity", sans: "परिचयम्" },
{ en: "if", sans: "यदि" },
{ en: "in front of", sans: "पुरतः" },
{ en: "in seeing", sans: "दर्शने" },
{ en: "indeed", sans: "एव" },
{ en: "inside", sans: "अन्तः" },
{ en: "landlord", sans: "भूस्वामी" },
{ en: "loss", sans: "हानिः?" },
{ en: "may return", sans: "आगच्छतु" },
{ en: "money", sans: "धनं" },
{ en: "must be", sans: "भवेत्" },
{ en: "not having recognized", sans: "अप्राप्तवान्" },
{ en: "not", sans: "न" },
{ en: "not", sans: "मा" },
{ en: "of many shawls", sans: "राङ्कवानाम्" },
{ en: "once", sans: "एकवारं" },
{ en: "once", sans: "कदाचित्" },
{ en: "or", sans: "वा" },
{ en: "people", sans: "जनाः" },
{ en: "pleased", sans: "सन्तुष्टः" },
{ en: "present (arrived)", sans: "उपस्थितः" },
{ en: "price", sans: "मूल्यम्" },
{ en: "returned", sans: "प्रत्यागच्छत्" },
{ en: "said", sans: "उक्तवान्" },
{ en: "shawl", sans: "राङ्कवः" },
{ en: "shop's", sans: "आपणस्य" },
{ en: "shop", sans: "आपणः" },
{ en: "shopkeeper's", sans: "आपणिकस्य" },
{ en: "someone", sans: "कश्चित्" },
{ en: "stood", sans: "स्थितवान्" },
{ en: "the owner", sans: "आपणस्वामी" },
{ en: "the shawl", sans: "राङ्कवं" },
{ en: "the shopkeeper", sans: "आपणिकः" },
{ en: "then", sans: "तर्हि" },
{ en: "think", sans: "चिन्तयन्ति" },
{ en: "this (masculine)", sans: "एषः" },
{ en: "this", sans: "एतं" },
{ en: "thus", sans: "इति" },
{ en: "to Devarāja", sans: "देवराजाय" },
{ en: "wear", sans: "धरति" },
{ en: "what (feminine)", sans: "का" },
{ en: "with respectful hospitality", sans: "आदरातिथ्येन" },
{ en: "work (plural)", sans: "कार्याणि" },
{ en: "worn (by)", sans: "धृतवान्" },
{ en: "you (objective)", sans: "भवन्तं" },
{ en: "you may buy", sans: "क्रीणातु," },
{ en: "you may come", sans: "आगच्छतु" },
{ en: "you", sans: "भवान्" },
];
