const quizData = [
{ en: "accepted", sans: "अङ्गीकृतवन्तः" },
{ en: "also", sans: "अपि" },
{ en: "and", sans: "च" },
{ en: "arose", sans: "उत्पन्नः" },
{ en: "as the people's representative", sans: "प्रजाप्रतिनिधित्वेन" },
{ en: "asked", sans: "पृष्टवन्तः" },
{ en: "at night", sans: "रात्रौ" },
{ en: "because", sans: "यतः" },
{ en: "but", sans: "किन्तु" },
{ en: "by name", sans: "नाम" },
{ en: "by roaming", sans: "अटनेन" },
{ en: "calmly", sans: "शान्तस्वरेण" },
{ en: "causes", sans: "जनयति" },
{ en: "confirmed", sans: "दृढीकृतः" },
{ en: "court", sans: "न्यायालयः" },
{ en: "days", sans: "दिनानि" },
{ en: "in days", sans: "दिनेषु" },
{ en: "decision-making authority", sans: "निर्णयाधिकारं" },
{ en: "decision", sans: "निर्णयः" },
{ en: "did", sans: "कृतवान्" },
{ en: "dispute-causing", sans: "विवादजनकं" },
{ en: "dispute's", sans: "विवादस्य" },
{ en: "dispute", sans: "विवादं" },
{ en: "doubt", sans: "सन्देहः" },
{ en: "even if", sans: "चेदपि" },
{ en: "finally", sans: "अन्ते" },
{ en: "had to be sent", sans: "प्रेषणीयः आसीत्" },
{ en: "here", sans: "अत्र" },
{ en: "if", sans: "यदि" },
{ en: "in disguise", sans: "वेषान्तरेण" },
{ en: "in that", sans: "तस्मिन्" },
{ en: "in the capital", sans: "राजधान्याम्" },
{ en: "in the past two or three", sans: "गतद्वित्रेषु" },
{ en: "in the village", sans: "ग्रामे" },
{ en: "in villages", sans: "ग्रामेषु" },
{ en: "indeed", sans: "एव" },
{ en: "isn't it so?”", sans: "किल" },
{ en: "let (him) go", sans: "गच्छतु" },
{ en: "made", sans: "कृतवन्तः" },
{ en: "movement / roaming", sans: "सञ्चारं" },
{ en: "must go", sans: "गन्तव्यः" },
{ en: "my", sans: "मम" },
{ en: "of the village head", sans: "ग्रामप्रमुखस्य" },
{ en: "once", sans: "एकदा" },
{ en: "only", sans: "एव" },
{ en: "peace", sans: "शान्तिः" },
{ en: "present", sans: "उपस्थितः" },
{ en: "real", sans: "वास्तविकः" },
{ en: "regarding the dispatch", sans: "प्रेषणविषये" },
{ en: "regarding this", sans: "एतद्विषये" },
{ en: "said", sans: "उक्तवान्" },
{ en: "sent", sans: "प्रेषितवन्तः" },
{ en: "shall we send?", sans: "प्रेषयामः वा?" },
{ en: "small", sans: "लघु" },
{ en: "someone", sans: "कश्चित्" },
{ en: "someone’s", sans: "कस्यापि" },
{ en: "statement", sans: "वचनम्" },
{ en: "that", sans: "तं" },
{ en: "the people's representative", sans: "प्रजाप्रतिनिधिं" },
{ en: "the village head", sans: "ग्रामप्रमुखः" },
{ en: "the villagers", sans: "ग्रामवासिनः" },
{ en: "then", sans: "तदा" },
{ en: "than", sans: "तर्हि" },
{ en: "there", sans: "तत्र" },
{ en: "therefore", sans: "अतः" },
{ en: "they", sans: "ते" },
{ en: "this", sans: "एतस्य" },
{ en: "thus", sans: "इति" },
{ en: "to the capital", sans: "राजधानीं" },
{ en: "two or three", sans: "दित्राणि" },
{ en: "unanimous opinion", sans: "एकाभिप्रायः" },
{ en: "under the control", sans: "अधीनं" },
{ en: "until", sans: "यावत्" },
{ en: "used to be", sans: "भवति स्म" },
{ en: "used to say", sans: "वदति स्म" },
{ en: "village", sans: "ग्रामः" },
{ en: "villager's", sans: "ग्रामीणानाम्" },
{ en: "villagers", sans: "ग्रामीणाः" },
{ en: "was not there", sans: "न आसीत्" },
{ en: "was", sans: "आसीत्" },
{ en: "we send", sans: "प्रेषयामः" },
{ en: "well-provided / prosperous", sans: "सुसम्पन्नः" },
{ en: "wherever", sans: "यत्र कुत्रापि" },
{ en: "will not happen", sans: "न भविष्यति" },
{ en: "will pervade", sans: "व्याप्ता भवति" },
{ en: "will reside", sans: "निवसेत्" },
{ en: "with one accord", sans: "ऐकमत्येन" },
{ en: "with surprise", sans: "आश्चर्येण" },
{ en: "yes", sans: "आम्" },
];
