const quizData = [
{ en: "afraid", sans: "भीतः" },
{ en: "after bowing", sans: "नमस्कृत्य" },
{ en: "all", sans: "सर्वम्" },
{ en: "always", sans: "सदा" },
{ en: "and", sans: "च" },
{ en: "any", sans: "कोऽपि" },
{ en: "asked", sans: "पृष्टवान्" },
{ en: "at some time / once", sans: "कदाचित्" },
{ en: "body", sans: "देहः" },
{ en: "but", sans: "किन्तु" },
{ en: "by grace", sans: "अनुग्रहेण" },
{ en: "Chitrapura's", sans: "चित्रपुरस्य" },
{ en: "coming / visit", sans: "आगमनं" },
{ en: "death's", sans: "मरणस्य" },
{ en: "death", sans: "मरणम्" },
{ en: "desire", sans: "इच्छति" },
{ en: "even", sans: "अपि" },
{ en: "even", sans: "एव" },
{ en: "fear of death", sans: "मरण भीतिः" },
{ en: "fear", sans: "भीतिः" },
{ en: "for preventing death", sans: "मरणनिवारणार्थम्" },
{ en: "from death", sans: "मरणात्" },
{ en: "from the mouth", sans: "मुखतः" },
{ en: "gentle smile", sans: "मन्दहासं" },
{ en: "has become", sans: "जातम्" },
{ en: "having expressed", sans: "निवेद्य" },
{ en: "having said", sans: "उक्त्वा" },
{ en: "he", sans: "सः" },
{ en: "hearing ability", sans: "श्रवणशक्तिः" },
{ en: "hermitage", sans: "आश्रमं" },
{ en: "his own", sans: "आत्मनः" },
{ en: "hope, desire", sans: "आशा" },
{ en: "I remain", sans: "भवामि" },
{ en: "I will attain", sans: "प्राप्स्यामि" },
{ en: "I", sans: "अहं" },
{ en: "in his mind", sans: "तस्य मनसि" },
{ en: "in me", sans: "मयि" },
{ en: "in such a situation", sans: "एवं स्थिते" },
{ en: "in such a way", sans: "तथा" },
{ en: "in the forest", sans: "अरण्ये" },
{ en: "in this", sans: "अस्याम्" },
{ en: "in youth", sans: "तारुण्ये" },
{ en: "is there?", sans: "अस्ति वा" },
{ en: "Jñānānanda's", sans: "ज्ञानानन्दस्य" },
{ en: "just like this", sans: "एवम् एव" },
{ en: "just now / immediately", sans: "सद्यः एव" },
{ en: "king", sans: "राजा" },
{ en: "know", sans: "जानन्ति" },
{ en: "knowers of the three times (past, present, future)", sans: "त्रिकालज्ञाः" },
{ en: "later in time", sans: "कालान्तरे" },
{ en: "matter / subject", sans: "विषयं" },
{ en: "may occur", sans: "भवेत्" },
{ en: "method, way", sans: "उपायः" },
{ en: "minister", sans: "मन्त्री" },
{ en: "my", sans: "मम" },
{ en: "nearby", sans: "समीपे" },
{ en: "not", sans: "न" },
{ en: "now", sans: "इदानीम्" },
{ en: "O great king", sans: "महाराज" },
{ en: "O great soul", sans: "महात्मन्" },
{ en: "obtaining", sans: "प्राप्य" },
{ en: "of Sage Jñānānanda", sans: "ज्ञानानन्दमुनेः" },
{ en: "old", sans: "वृद्धः" },
{ en: "only", sans: "एव" },
{ en: "penance", sans: "तपः" },
{ en: "performing", sans: "आचरतः" },
{ en: "return", sans: "आगच्छतु"},
{ en: "said", sans: "उक्तवान्" },
{ en: "should be searched", sans: "अन्वेष्टव्यः" },
{ en: "should live long", sans: "चिरं जीवितव्यम्" },
{ en: "showing, revealing", sans: "प्रकटयन्" },
{ en: "audience", sans: "दर्शनं" },
{ en: "sight", sans: "दृष्टिः" },
{ en: "state, condition", sans: "अवस्थायाम्" },
{ en: "still", sans: "अपि" },
{ en: "successful", sans: "सफलं" },
{ en: "such that", sans: "यथा" },
{ en: "suddenly", sans: "अकस्मात्" },
{ en: "teeth", sans: "दन्ताः" },
{ en: "that fear", sans: "इति भीतिः" },
{ en: "then", sans: "तदा" },
{ en: "there", sans: "तत्र" },
{ en: "therefore", sans: "अतः" },
{ en: "thinking thus", sans: "इति चिन्तयन्" },
{ en: "this", sans: "एतं" },
{ en: "thus", sans: "इति" },
{ en: "to do", sans: "कर्तुं" },
{ en: "to the capital", sans: "राजधानीं" },
{ en: "weak", sans: "दुर्बलः" },
{ en: "why", sans: "किमर्थम्" },
{ en: "will diminish", sans: "क्षीणा भविष्यति" },
{ en: "wisdom", sans: "विवेकः" },
{ en: "you (honorific)", sans: "भवान्" },
{ en: "you (plural)", sans: "भवन्तः" },
{ en: "you", sans: "भवान्" },
{ en: "your", sans: "भवतः" },
];
