const quizData = [
{ en: "a certain", sans: "कश्चन" },
{ en: "a fellow villager", sans: "तद्ग्रामीणः" },
{ en: "a person called Sharabha", sans: "शरभः" },
{ en: "a person named रामचन्द्र", sans: "रामचन्द्रः" },
{ en: "after extinguishing", sans: "निर्वाप्य" },
{ en: "after his arrival", sans: "आगमनानन्तरम्" },
{ en: "after much contemplation", sans: "बहुचिन्तनानन्तरम्" },
{ en: "again", sans: "पुनः" },
{ en: "again", sans: "पुनश्च" },
{ en: "among the rich", sans: "धनिकपङ्क्तौ" },
{ en: "also", sans: "अपि" },
{ en: "and", sans: "च" },
{ en: "anything", sans: "किमपि" },
{ en: "asked", sans: "पृष्टवान्" },
{ en: "at the time of arrival", sans: "आगमनसमये" },
{ en: "attained", sans: "प्राप्तवान्" },
{ en: "become", sans: "जातः" },
{ en: "before", sans: "पूर्वम्" },
{ en: "besides Sharaba", sans: "शरभस्य पार्श्वे" },
{ en: "burns", sans: "ज्वलति" },
{ en: "by your behavior", sans: "भवतः व्यवहारेण" },
{ en: "comfortably", sans: "सुखम्" },
{ en: "conversation", sans: "वार्तालापं" },
{ en: "did not understand", sans: "न ज्ञातवान्" },
{ en: "duration", sans: "अवधौ" },
{ en: "empty handed", sans: "रिक्तहस्तेन" },
{ en: "expressing", sans: "प्रकटयन्" },
{ en: "first", sans: "प्रथमं" },
{ en: "for an important reason", sans: "विशेषकारणेन" },
{ en: "for conversation", sans: "वार्तालापार्थ" },
{ en: "friends", sans: "स्नेहितौ" },
{ en: "from the same village", sans: "समानग्रामीणौ" },
{ en: "from there", sans: "ततः" },
{ en: "from your words", sans: "भवत्कथनतः" },
{ en: "getting up", sans: "उत्थाय" },
{ en: "happiness", sans: "सन्तोषं" },
{ en: "has come", sans: "आगतवान्" },
{ en: "having gone", sans: "गत्वा" },
{ en: "having lit, after lighting", sans: "प्रज्वाल्य" },
{ en: "he", sans: "सः" },
{ en: "hearing", sans: "श्रुत्वा" },
{ en: "here", sans: "अत्र" },
{ en: "his doubt", sans: "स्वकीयसन्देहं" },
{ en: "house", sans: "गृहं" },
{ en: "how", sans: "कथं" },
{ en: "I", sans: "अहम्" },
{ en: "if", sans: "चेत्" },
{ en: "in a casual tone", sans: "सहजस्वरेण" },
{ en: "in the evening", sans: "सायङ्काले" },
{ en: "in the middle", sans: "मध्ये" },
{ en: "in the room", sans: "प्रकोष्ठे" },
{ en: "in vain", sans: "वृथा" },
{ en: "indeed, certainly", sans: "एव" },
{ en: "indeed", sans: "किल" },
{ en: "inside", sans: "अन्तः" },
{ en: "is not", sans: "नास्ति" },
{ en: "isn't it", sans: "किल" },
{ en: "it's", sans: "तस्य" },
{ en: "lamp", sans: "दीपं" },
{ en: "land", sans: "भूमिं" },
{ en: "let us have", sans: "कुर्मः" },
{ en: "must be known", sans: "ज्ञातव्यम्" },
{ en: "not", sans: "न" },
{ en: "now", sans: "इदानीं" },
{ en: "ok", sans: "अस्तु" },
{ en: "on the ground", sans: "भूमौ" },
{ en: "once, one day", sans: "एकदा" },
{ en: "one, a single", sans: "एकं" },
{ en: "outside", sans: "बहिः" },
{ en: "place", sans: "स्थानं" },
{ en: "quickly", sans: "झटिति" },
{ en: "Ramachandra's", sans: "रामचन्द्रस्य" },
{ en: "reason", sans: "कारणं" },
{ en: "respectfully", sans: "आदरपूर्वकम्" },
{ en: "reveal", sans: "निवेदयति" },
{ en: "said", sans: "उक्तवान्" },
{ en: "say, tell", sans: "वदतु" },
{ en: "saying", sans: "उक्त्वा" },
{ en: "saying", sans: "वदन्" },
{ en: "secret", sans: "रहस्यम्" },
{ en: "seeing, after seeing", sans: "दृष्ट्वा" },
{ en: "should be done", sans: "करणीयः" },
{ en: "sitting", sans: "उपविश्य" },
{ en: "sitting", sans: "उपविश्य" },
{ en: "small mat", sans: "लघुकटं" },
{ en: "some secret", sans: "किमपि रहस्यं" },
{ en: "somehow, by some means", sans: "कथञ्चित्" },
{ en: "spreading", sans: "प्रसार्य" },
{ en: "that", sans: "तं" },
{ en: "that", sans: "तत्" },
{ en: "the lamp", sans: "दीपः" },
{ en: "then, at that time", sans: "तदा" },
{ en: "there", sans: "तत्र" },
{ en: "thinking", sans: "चिन्तयन्" },
{ en: "this", sans: "एतत्" },
{ en: "thus, so", sans: "इति" },
{ en: "thus", sans: "तथा" },
{ en: "to his home", sans: "स्वगृहं" },
{ en: "to me", sans: "मह्यं" },
{ en: "unexpected expenditure", sans: "अनपेक्षितव्ययः" },
{ en: "village", sans: "ग्रामं" },
{ en: "we shall meet", sans: "मिलामः" },
{ en: "we two", sans: "आवां" },
{ en: "wealthy man", sans: "धनिकः" },
{ en: "went", sans: "गतवान्" },
{ en: "what", sans: "किं" },
{ en: "why did you extinguish", sans: "किमर्थं निर्वापितवान्" },
{ en: "why is a lamp required", sans: "दीपः किमर्थम्?" },
{ en: "why", sans: "किमर्थं" },
{ en: "with astonishment", sans: "आश्चर्येण" },
{ en: "within a short", sans: "अल्पे" },
{ en: "within a year", sans: "एकवर्षाभ्यन्तरे" },
{ en: "within five years", sans: "पञ्चवर्षाभ्यन्तरे" },
];
