const quizData = [
{ en: "Which student goes?", sans: "कः छात्रः गच्छति?" },
{ en: "Who are those teachers?", sans: "ते अध्यापकाः के?" },
{ en: "Who are these girls?", sans: "एताः बालिकाः काः?" },
{ en: "Who are these maidservants?", sans: "एताः सेविकाः काः?" },
{ en: "Which farmer writes?", sans: "कः कृषकः लिखति?" },
{ en: "Who is this merchant?", sans: "एषः वणिक् कः?" },
{ en: "What are those two fruits?", sans: "ते फले के?" },
{ en: "Who are these boys?", sans: "एते बालकाः के?" },
{ en: "Which merchant goes?", sans: "कः वणिक् गच्छति?" },
{ en: "Who are these two boys?", sans: "एतौ बालकौ कौ?" },
{ en: "Who is this teacher?", sans: "एषः अध्यापकः कः?" },
{ en: "Which servant runs?", sans: "कः सेवकः धावति?" },
{ en: "Who are those princes?", sans: "ते कुमाराः के?" },
{ en: "Which maidservant runs?", sans: "का सेविका धावति?" },
{ en: "Which queen reads?", sans: "का राज्ञी पठति?" },
{ en: "Which boy writes?", sans: "कः बालकः लिखति?" },
{ en: "Which teacher sees?", sans: "का अध्यापिका पश्यति?" },
{ en: "Who are these two students?", sans: "एतौ छात्रौ कौ?" },
{ en: "Who is that farmer (feminine)?", sans: "सा कृषिका का?" },
{ en: "Who are those servants?", sans: "ते सेवकाः के?" },
{ en: "Who is this farmer?", sans: "एषः कृषकः कः?" },
{ en: "Who are those teachers?", sans: "ताः अध्यापिकाः काः?" },
{ en: "Who is that teacher?", sans: "सः अध्यापकः कः?" },
{ en: "Who is this queen?", sans: "एषा राज्ञी का?" },
{ en: "What are those two houses?", sans: "ते गृहे के?" },
{ en: "Who are those two servants?", sans: "तौ सेवकौ कौ?" },
{ en: "What are these two fruits?", sans: "एते फले के?" },
{ en: "Who is this maidservant?", sans: "एषा सेविका का?" },
{ en: "Who is this friend?", sans: "एतत् मित्रम् किम्?" },
/* was here */
{ en: "Who are these two friends?", sans: "एतौ मित्रे कौ?" },
{ en: "Who are those maidservants?", sans: "ताः सेविकाः काः?" },
{ en: "Which boy writes?", sans: "एषः कः बालकः लिखति?" },
{ en: "Who are those two doctors?", sans: "तौ वैद्यौ कौ?" },
{ en: "What is this book?", sans: "एतत् किं पुस्तकम्?" },
{ en: "Who is this teacher?", sans: "एषा अध्यापिका का?" },
{ en: "Which teacher sees?", sans: "एषा का अध्यापिका पश्यति?" },
{ en: "What are these two houses?", sans: "एते के गृहे?" },
{ en: "Who is this servant?", sans: "एषः सेवकः कः?" },
{ en: "Who are these merchants?", sans: "एते वणिजः के?" },
{ en: "Who is that maidservant?", sans: "सा सेविका का?" },
{ en: "Who are those two merchants?", sans: "तौ कौ वणिजौ?" },
{ en: "What is this house?", sans: "एतत् किं गृहम्?" },
{ en: "Who are those merchants?", sans: "ते के वणिजः?" },
{ en: "Who are those friends?", sans: "ते के मित्राणि?" },
{ en: "Who are those kings?", sans: "ते के राजानः?" },
{ en: "Who are those doctors?", sans: "ते के वैद्याः?" },
{ en: "Who is that girl?", sans: "सा का बालिका?" },
{ en: "What is that letter?", sans: "तत् किं पत्रम्?" },
{ en: "Who are those two teachers?", sans: "तौ कौ अध्यापकौ?" },
{ en: "Who are these teachers?", sans: "एताः काः अध्यापिकाः?" },
{ en: "Who are these friends?", sans: "एते के मित्राणि?" },
{ en: "Who are these servants?", sans: "एते के सेवकाः?" },
{ en: "What is this fruit?", sans: "एतत् किं फलम्?" },
{ en: "Who is this friend?", sans: "एषा का सखी?" },
{ en: "Which farmer writes?", sans: "सः कः कृषकः लिखति?" },
{ en: "Who are these two farmers?", sans: "एतौ कौ कृषकौ?" },
{ en: "Who are these farmers?", sans: "एते के कृषकाः?" },
{ en: "Who are these two kings?", sans: "एतौ कौ राजानौ?" },
{ en: "What is that house?", sans: "तत् किं गृहम्?" },
{ en: "Who are these princes?", sans: "एते के कुमाराः?" },
{ en: "Who are these students?", sans: "एताः काः छात्राः?" },
{ en: "Who are those two friends?", sans: "तौ कौ मित्रे?" },
{ en: "Who are these kings?", sans: "एते के राजानः?" },
{ en: "Who is this student?", sans: "एषा का छात्रा?" },
{ en: "What are these two flowers?", sans: "एते के पुष्पे?" },
{ en: "What are those houses?", sans: "तानि कानि गृहाणि?" },
{ en: "What are those fruits?", sans: "तानि कानि फलानि?" },
{ en: "Who is this female doctor?", sans: "एषा का वैद्या?" },
{ en: "Who is this boy?", sans: "एषः कः बालकः?" },
{ en: "Which teacher sees?", sans: "सः कः अध्यापकः पश्यति?" },
{ en: "Who is that friend?", sans: "सा का सखी?" },
{ en: "Who is this king?", sans: "एषः कः राजा?" },
{ en: "Who is this farmer's wife?", sans: "एषा का कृषिका?" },
{ en: "Who are these women?", sans: "एताः काः राज्ञ्यः?" },
{ en: "Who are those two farmers?", sans: "तौ कौ कृषकौ?" },
{ en: "Who are those boys?", sans: "ते के बालकाः?" },
{ en: "Which king reads?", sans: "सः कः राजा पठति?" },
{ en: "Who are these two teachers?", sans: "एतौ कौ अध्यापकौ?" },
{ en: "Who are those two princes?", sans: "तौ कौ कुमारौ?" },
{ en: "What are those two letters?", sans: "ते के पत्रे?" },
{ en: "What are those two flowers?", sans: "ते के पुष्पे?" },
{ en: "Which king reads?", sans: "एषः कः राजा पठति?" },
{ en: "Who is that servant?", sans: "सः कः सेवकः?" },
{ en: "Who is that princess?", sans: "सा का कुमारी?" },
{ en: "Who is this prince?", sans: "एषः कः कुमारः?" },
{ en: "Who are these doctors?", sans: "एते के वैद्याः?" },
{ en: "What is that book?", sans: "तत् किं पुस्तकम्?" },
{ en: "Who is that student?", sans: "सः कः छात्रः?" },
{ en: "Who is that merchant?", sans: "सः कः वणिक्?" },
{ en: "Who are those two boys?", sans: "तौ कौ बालकौ?" },
{ en: "Who is this merchant woman?", sans: "एषा का वणिजा?" },
{ en: "Who are these two doctors?", sans: "एतौ कौ वैद्यौ?" },
{ en: "Which student goes?", sans: "सः कः छात्रः गच्छति?" },
{ en: "Which doctor reads?", sans: "एषः कः वैद्यः पठति?" },
{ en: "Which friend runs?", sans: "एतत् किं मित्रम् धावति?" },
{ en: "Who is this princess?", sans: "एषा का कुमारी?" },
{ en: "Which teacher sees?", sans: "एषः कः अध्यापकः पश्यति?" },
{ en: "Who are those students?", sans: "ते के छात्राः?" },
{ en: "What are those books?", sans: "तानि कानि पुस्तकानि?" },
{ en: "Which girl writes?", sans: "एषा का बालिका लिखति?" },
{ en: "Which student goes?", sans: "सा का छात्रा गच्छति?" },
{ en: "Who is this student?", sans: "एषः कः छात्रः?" },
{ en: "Who are those two students?", sans: "तौ कौ छात्रौ?" },
{ en: "What is that flower?", sans: "तत् किं पुष्पम्?" },
{ en: "Who are those students?", sans: "ताः काः छात्राः?" },
{ en: "What are those letters?", sans: "तानि कानि पत्राणि?" },
{ en: "Which doctor reads?", sans: "सः कः वैद्यः पठति?" },
{ en: "Who are these students?", sans: "एते के छात्राः?" },
{ en: "Who is that king?", sans: "सः कः राजा?" },
{ en: "Who are those girls?", sans: "ताः काः बालिकाः?" },
{ en: "What are these two books?", sans: "एते के पुस्तके?" },
{ en: "What are these two letters?", sans: "एते के पत्रे?" },
{ en: "Which queen reads?", sans: "सा का राज्ञी पठति?" },
{ en: "What are these letters?", sans: "एतानि कानि पत्राणि?" },
{ en: "Which prince sees?", sans: "एषः कः कुमारः पश्यति?" },
{ en: "Which merchant goes?", sans: "एषः कः वणिक् गच्छति?" },
{ en: "What is that fruit?", sans: "तत् किं फलम्?" },
{ en: "Who is that queen?", sans: "सा का राज्ञी?" },
{ en: "Who is this doctor?", sans: "एषः कः वैद्यः?" },
{ en: "Which girl writes?", sans: "सा का बालिका लिखति?" },
{ en: "Who is that farmer?", sans: "सः कः कृषकः?" },
{ en: "What is this flower?", sans: "एतत् किं पुष्पम्?" },
{ en: "What is this letter?", sans: "एतत् किं पत्रम्?" },
{ en: "Who is this girl?", sans: "एषा का बालिका?" },
{ en: "Which student goes?", sans: "एषा का छात्रा गच्छति?" },
{ en: "Which maidservant runs?", sans: "सा का सेविका धावति?" },
{ en: "Who are those women?", sans: "ताः काः राज्ञ्यः?" },
{ en: "What are those two books?", sans: "ते के पुस्तके?" },
{ en: "Who is that friend?", sans: "सः कः मित्रम्?" },
{ en: "What are these flowers?", sans: "एतानि कानि पुष्पाणि?" },
{ en: "Which servant runs?", sans: "एषः कः सेवकः धावति?" },
{ en: "Who are these teachers?", sans: "एते के अध्यापकाः?" },
{ en: "Who is that student?", sans: "सा का छात्रा?" },
{ en: "Who is that prince?", sans: "सः कः कुमारः?" },
{ en: "Who is that boy?", sans: "सः कः बालकः?" },
{ en: "Who are these two servants?", sans: "एतौ कौ सेवकौ?" },
{ en: "Who is that teacher?", sans: "सा का अध्यापिका?" },
{ en: "Which prince sees?", sans: "सः कः कुमारः पश्यति?" },
{ en: "Who is that doctor?", sans: "सः कः वैद्यः?" },
{ en: "Who are these two princes?", sans: "एतौ कौ कुमारौ?" },
{ en: "Who is that merchant woman?", sans: "सा का वणिजा?" },
{ en: "What are these fruits?", sans: "एतानि कानि फलानि?" },
{ en: "Who are those two kings?", sans: "तौ कौ राजानौ?" },
{ en: "Who are those farmers?", sans: "ते के कृषकाः?" },
{ en: "Who is that female doctor?", sans: "सा का वैद्या?" },
{ en: "Who are these two merchants?", sans: "एतौ कौ वणिजौ?" },
{ en: "Which friend runs?", sans: "सः किं मित्रम् धावति?" },
{ en: "What are these books?", sans: "एतानि कानि पुस्तकानि?" },
{ en: "What are those flowers?", sans: "तानि कानि पुष्पाणि?" },
];

