const quizData = [
{ en: "Which student goes?", sans: "कः छात्रः गच्छति?" },
{ en: "Who are those teachers?", sans: "ते अध्यापकाः के?" },
{ en: "Who are these girls?", sans: "एताः बालिकाः काः?" },
{ en: "Who are these maidservants?", sans: "एताः सेविकाः काः?" },
{ en: "Which farmer writes?", sans: "कः कृषकः लिखति?" },
{ en: "Who is this merchant?", sans: "एषः वणिक् कः?" },
{ en: "What are those two fruits?", sans: "ते फले के?" },
{ en: "Who are these boys?", sans: "एते बालकाः के?" },
{ en: "Which merchant goes?", sans: "कः वणिक् गच्छति?" },
{ en: "Who are these two boys?", sans: "एतौ बालकौ कौ?" },
{ en: "Who is this teacher?", sans: "एषः अध्यापकः कः?" },
{ en: "Which servant runs?", sans: "कः सेवकः धावति?" },
{ en: "Who are those princes?", sans: "ते कुमाराः के?" },
{ en: "Which maidservant runs?", sans: "का सेविका धावति?" },
{ en: "Which queen reads?", sans: "का राज्ञी पठति?" },
{ en: "Which boy writes?", sans: "कः बालकः लिखति?" },
{ en: "Which teacher sees?", sans: "का अध्यापिका पश्यति?" },
{ en: "Who are these two students?", sans: "एतौ छात्रौ कौ?" },
{ en: "Who is that farmer (feminine)?", sans: "सा कृषिका का?" },
{ en: "Who are those servants?", sans: "ते सेवकाः के?" },
{ en: "Who is this farmer?", sans: "एषः कृषकः कः?" },
{ en: "Who are those teachers?", sans: "ताः अध्यापिकाः काः?" },
{ en: "Who is that teacher?", sans: "सः अध्यापकः कः?" },
{ en: "Who is this queen?", sans: "एषा राज्ञी का?" },
{ en: "What are those two houses?", sans: "ते गृहे के?" },
{ en: "Who are those two servants?", sans: "तौ सेवकौ कौ?" },
{ en: "What are these two fruits?", sans: "एते फले के?" },
{ en: "Who is this maidservant?", sans: "एषा सेविका का?" },
{ en: "Who is this friend?", sans: "एतत् मित्रम् किम्?" },
{ en: "Who are these two friends?", sans: "एते मित्रे के?" },
{ en: "Who are those maidservants?", sans: "ताः सेविकाः काः?" },
{ en: "Which boy writes?", sans: "कः बालकः लिखति?" },
{ en: "Who are those two doctors?", sans: "तौ वैद्यौ कौ?" },
{ en: "What is this book?", sans: "एतत् पुस्तकम् किं?" },
{ en: "Who is this teacher?", sans: "एषा अध्यापिका का?" },
{ en: "Which teacher sees?", sans: "का अध्यापिका पश्यति?" },
{ en: "What are these two houses?", sans: "एते गृहे के?" },
{ en: "Who is this servant?", sans: "एषः सेवकः कः?" },
{ en: "Who are these merchants?", sans: "एते वणिजः के?" },
{ en: "Who is that maidservant?", sans: "सा सेविका का?" },
{ en: "Who are those two merchants?", sans: "तौ वणिजौ कौ?" },
{ en: "Who are those merchants?", sans: "ते वणिजः के?" },
{ en: "Who are those friends?", sans: "तानि मित्राणि कानि?" },
{ en: "Who are those kings?", sans: "ते राजानः के?" },
{ en: "Who are those doctors?", sans: "ते वैद्याः के?" },
{ en: "Who is that girl?", sans: "सा बालिका का?" },
{ en: "What is that letter?", sans: "तत् पत्रम् किं?" },
{ en: "Who are those two teachers?", sans: "तौ अध्यापकौ कौ?" },
{ en: "Who are these teachers?", sans: "एताः अध्यापिकाः काः?" },
{ en: "Who are these friends?", sans: "एतानि मित्राणि कानि?" },
{ en: "Who are these servants?", sans: "एते सेवकाः के?" },
{ en: "What fruit is this?", sans: "एतत् किं फलम्?" },
{ en: "Who is this friend?", sans: "एषा सखी का?" },
{ en: "Which farmer writes?", sans: "कः कृषकः लिखति?" },
{ en: "Who are these two farmers?", sans: "एतौ कृषकौ कौ?" },
{ en: "Who are these farmers?", sans: "एते कृषकाः के?" },
{ en: "Who are these two kings?", sans: "एतौ राजानौ कौ?" },
{ en: "Who are these princes?", sans: "एते कुमाराः के?" },
{ en: "Who are these students (feminine)?", sans: "एताः छात्राः काः?" },
{ en: "Who are those two friends?", sans: "ते मित्रे के?" },
{ en: "Who are these kings?", sans: "एते राजानः के?" },
{ en: "Who is this student?", sans: "एषा छात्रा का?" },
{ en: "What are these two flowers?", sans: "एते पुष्पे के?" },
{ en: "What are those fruits?", sans: "तानि फलानि कानि?" },
{ en: "Who is this doctor (feminine) ?", sans: "एषा वैद्या का?" },
{ en: "Who is this boy?", sans: "एषः बालकः कः?" },
{ en: "Which teacher sees?", sans: "कः अध्यापकः पश्यति?" },
{ en: "Who is that friend (feminine)?", sans: "सा सखी का?" },
{ en: "Who is this king?", sans: "एषः राजा कः?" },
{ en: "Who is this farmer's wife?", sans: "एषा कृषिका का?" },
{ en: "Who are these women?", sans: "एताः राज्ञ्यः काः?" },
{ en: "Who are those two farmers?", sans: "तौ कृषकौ कौ?" },
{ en: "Who are those boys?", sans: "ते बालकाः के?" },
{ en: "Which king reads?", sans: "कः राजा पठति?" },
{ en: "Who are these two teachers?", sans: "एतौ अध्यापकौ कौ?" },
{ en: "Who are those two princes?", sans: "तौ कुमारौ कौ?" },
{ en: "What are those two letters?", sans: "ते पत्रे के?" },
{ en: "What are those two flowers?", sans: "ते पुष्पे के?" },
{ en: "Which king reads?", sans: "कः राजा पठति?" },
{ en: "Who is that servant?", sans: "सः सेवकः कः?" },
{ en: "Who is that princess?", sans: "सा कुमारी का?" },
{ en: "Who is this prince?", sans: "एषः कुमारः कः?" },
{ en: "Who are these doctors (masculine)?", sans: "एते वैद्याः के?" },
{ en: "What is that book?", sans: "तत् पुस्तकम् किं?" },
{ en: "Who is that student?", sans: "सः छात्रः कः?" },
{ en: "Who is that merchant?", sans: "सः वणिक् कः?" },
{ en: "Who are those two boys?", sans: "तौ बालकौ कौ?" },
{ en: "Who is this merchant woman?", sans: "एषा वणिजा का?" },
{ en: "Who are these two doctors?", sans: "एतौ वैद्यौ कौ?" },
{ en: "Which student goes?", sans: "कः छात्रः गच्छति?" },
{ en: "Which doctor reads?", sans: "कः वैद्यः पठति?" },
{ en: "Which friend runs?", sans: "किं मित्रम् धावति?" },
{ en: "Who is this princess?", sans: "एषा कुमारी का?" },
{ en: "Which teacher sees?", sans: "कः अध्यापकः पश्यति?" },
{ en: "Who are those students?", sans: "ते छात्राः के?" },
{ en: "What are those books?", sans: "तानि पुस्तकानि कानि?" },
{ en: "Which girl writes?", sans: "का बालिका लिखति?" },
{ en: "Which student goes?", sans: "का छात्रा गच्छति?" },
{ en: "Who is this student?", sans: "एषः छात्रः कः?" },
{ en: "Who are those two students?", sans: "तौ छात्रौ कौ?" },
{ en: "What is that flower?", sans: "तत् पुष्पम् किं?" },
{ en: "Who are those students?", sans: "ताः छात्राः काः?" },
{ en: "What are those letters?", sans: "तानि पत्राणि कानि?" },
{ en: "Which doctor reads?", sans: "कः वैद्यः पठति?" },
{ en: "Who are these students?", sans: "एते छात्राः के?" },
{ en: "Who is that king?", sans: "सः राजा कः?" },
{ en: "Who are those girls?", sans: "ताः बालिकाः काः?" },
{ en: "What are these two books?", sans: "एते पुस्तके के?" },
{ en: "What are these two letters?", sans: "एते पत्रे के?" },
{ en: "Which queen reads?", sans: "का राज्ञी पठति?" },
{ en: "What are these letters?", sans: "एतानि पत्राणि कानि?" },
{ en: "Which prince sees?", sans: "कः कुमारः पश्यति?" },
{ en: "Which merchant goes?", sans: "कः वणिक् गच्छति?" },
{ en: "What is that fruit?", sans: "तत् फलम् किं?" },
{ en: "Who is that queen?", sans: "सा राज्ञी का?" },
{ en: "Who is this doctor?", sans: "एषः वैद्यः कः?" },
{ en: "Which girl writes?", sans: "का बालिका लिखति?" },
{ en: "Who is that farmer?", sans: "सः कृषकः कः?" },
{ en: "What is this flower?", sans: "एतत् पुष्पम् किं?" },
{ en: "What is this letter?", sans: "एतत् पत्रम् किं?" },
{ en: "Who is this girl?", sans: "एषा बालिका का?" },
{ en: "Which student goes?", sans: "का छात्रा गच्छति?" },
{ en: "Which maidservant runs?", sans: "का सेविका धावति?" },
{ en: "Who are those women?", sans: "ताः राज्ञ्यः काः?" },
{ en: "What are those two books?", sans: "ते पुस्तके के?" },
{ en: "Who is that friend?", sans: "तत् मित्रम् किम्?" },
{ en: "What are these flowers?", sans: "एतानि पुष्पाणि कानि?" },
{ en: "Which servant runs?", sans: "कः सेवकः धावति?" },
{ en: "Who are these teachers?", sans: "एते अध्यापकाः के?" },
{ en: "Who is that student?", sans: "सा छात्रा का?" },
{ en: "Who is that prince?", sans: "सः कुमारः कः?" },
{ en: "Who is that boy?", sans: "सः बालकः कः?" },
{ en: "Who are these two servants?", sans: "एतौ सेवकौ कौ?" },
{ en: "Who is that teacher?", sans: "सा अध्यापिका का?" },
{ en: "Which prince sees?", sans: "कः कुमारः पश्यति?" },
{ en: "Who is that doctor?", sans: "सः वैद्यः कः?" },
{ en: "Who are these two princes?", sans: "एतौ कुमारौ कौ?" },
{ en: "Who is that merchant woman?", sans: "सा वणिजा का?" },
{ en: "What are these fruits?", sans: "एतानि फलानि कानि?" },
{ en: "Who are those two kings?", sans: "तौ राजानौ कौ?" },
{ en: "Who are those farmers?", sans: "ते कृषकाः के?" },
{ en: "Who is that female doctor?", sans: "सा वैद्या का?" },
{ en: "Who are these two merchants?", sans: "एतौ वणिजौ कौ?" },
{ en: "Which friend runs?", sans: "किं मित्रम् धावति?" },
{ en: "What are these books?", sans: "एतानि पुस्तकानि कानि?" },
{ en: "What are those flowers?", sans: "तानि पुष्पाणि कानि?" },
];

